In [15]:
import os
from dotenv import load_dotenv, find_dotenv
from pymongo import MongoClient
import pandas as pd
from pymongo.server_api import ServerApi

# Load environment variables
load_dotenv(find_dotenv())

# Connect to MongoDB
mongo_uri = os.environ['MONGO_URI']
client = MongoClient(mongo_uri, server_api=ServerApi('1'))

# TOP SALES PRODUCTS

In [16]:
# TOP SALES PRODUCTS
cm_env = os.environ.get('CM_ENV', 'dev')
if cm_env == 'prod':
    collection = client["campomaq"]["cm_top_sales_products"]
else:
    collection = client["campomaq_test"]["cm_top_sales_products"]

# Read all documents from the collection
cursor = collection.find({})
df_top_sales_prods = pd.DataFrame(list(cursor))

In [17]:
df_top_sales_prods

,_id,product_code,product_name,brand_name,category_name,quantity,sale_without_iva,total_cost,profit,main_boost,low_value_flag,quantity_norm,profit_norm,popularity
0,68c1c789c1cb16f9f3086e6b,408-0009SI,MOTOCULTOR TF545DE ARRANQUE ELECTRICO,HUSQVARNA,MOTOCULTORES,29,90930.000000,49013.093333,41916.906667,1,0,0.000306,1.000000,0.700122
1,68c1c789c1cb16f9f3086e6c,700-0001,MOTOCULTOR TKC-450,MITSUBISHI,MOTOCULTORES,8,43100.000000,21518.035814,21581.964186,1,0,0.000077,0.514875,0.457468
2,68c1c789c1cb16f9f3086e6d,700M-578,MOTOCULTOR TOPO Y LEVANTACAMAS,VARIOS MOTORES,MOTOCULTORES,3,13650.000000,10282.800000,3367.200000,1,0,0.000022,0.080330,0.240174
3,68c1c789c1cb16f9f3086e6e,700M-490SI,CUCHILLA CURVA IZQUIERDA APORCAR MOTOCULTOR TF...,HUSQVARNA,ACCESORIOS MOTOCULTORES,459,3701.345000,1044.225000,2657.120000,1,1,0.002002,0.063390,0.232496
4,68c1c789c1cb16f9f3086e6f,311-0012SI,CILINDRO BOMBA 653/655,MARUYAMA,REPUESTOS FUMIGACION,123,13197.000000,10627.200000,2569.800000,1,0,0.001333,0.061307,0.231187
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2606,68c1c789c1cb16f9f3087899,412-0037A,PISTON CPL 288,HUSQVARNA,REPUESTOS MOTOSIERRAS,1,11.700000,12.678609,0.010000,0,0,0.000000,0.000000,0.000000
2607,68c1c789c1cb16f9f308789a,700M-311,"LLAVE 3/4"" MEDIA VUELTA",VARIOS BOMBAS,ACCESORIOS DE RIEGO,1,6.521739,10.120000,0.010000,0,0,0.000000,0.000000,0.000000
2608,68c1c789c1cb16f9f308789b,440-0051,GUIA DE TEMPLADOR 365,HUSQVARNA,REPUESTOS MOTOSIERRAS,1,2.913043,4.953333,0.010000,0,0,0.000000,0.000000,0.000000
2609,68c1c789c1cb16f9f308789c,408-0032,PIÑON CON MANZANA 11 DIENTES MOTOAZADA TF545DE,HUSQVARNA,REPUESTOS MOTOCULTORES,1,7.058000,7.372190,0.010000,0,0,0.000000,0.000000,0.000000
2610,68c1c789c1cb16f9f308789d,403-0191,CILINDRO 236R,HUSQVARNA,REPUESTOS MOTOGUADANAS,1,0.000000,27.827901,0.010000,0,0,0.000000,0.000000,0.000000

In [18]:
df_top_sales_prods = df_top_sales_prods[["product_code", "main_boost", "low_value_flag", "popularity"]]

In [41]:
df_top_sales_prods.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2611 entries, 0 to 2610
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   product_code    2611 non-null   object
 1   main_boost      2611 non-null   int64
 2   low_value_flag  2611 non-null   int64
 3   popularity      2611 non-null   float64
dtypes: float64(1), int64(2), object(1)
memory usage: 81.7+ KB

# PRODUCT INFO

In [35]:
# PRODUCTS
cm_env = os.environ.get('CM_ENV', 'dev')
if cm_env == 'prod':
    collection = client["campomaq"]["cm_products"]
else:
    collection = client["campomaq_test"]["cm_products"]

# Read all documents from the collection
cursor = collection.find({})
df_products = pd.DataFrame(list(cursor))

df_products = df_products[~df_products["category_name"].str.lower().str.contains("servicios", na=False)]
df_products = df_products[~df_products["product_name"].str.lower().str.contains("varios", na=False)]

In [36]:
df_products

,_id,product_id,product_code,category_id,category_name,product_name,brand_id,brand_name,shelf_location,last_cost,avg_cost,price_cash,price_credit,price_card,product_type,iva,is_spare_part
0,68c1ec58f30a816cfad1c353,0,0,0,SIN CATEGORIA,.,0,S.M.,,100.000,-0.000,0.0000,120.000,0.0000,PO,False,False
1,68c1ec58f30a816cfad1c354,3368,700M-024,0,SIN CATEGORIA,GATO HIDRAULICO TIPO BOTELLA,17,VARIOS MOTORES,GENERAL,31.040,31.040,111.1525,114.487,116.7101,PO,True,False
2,68c1ec58f30a816cfad1c355,4167,700M-121,0,SIN CATEGORIA,TIJERA T-55C COSECHA Y PODA,17,VARIOS MOTORES,,16.441,16.441,0.0000,0.000,0.0000,PO,False,False
3,68c1ec58f30a816cfad1c356,1,101-0066SI,1,MOTOGUADANAS,"DESBROZADOR FS-450/ CUCHILLA, VISERA COMPLETA,...",13,STIHL,EST0102,770.880,0.000,902.9126,930.000,976.5000,PO,False,False
4,68c1ec58f30a816cfad1c357,803,305-0106SI,1,MOTOGUADANAS,DESBROZADORA B50R RIGIDA MARUYAMA,7,MARUYAMA,EST0401,621.775,621.770,776.6990,800.000,840.0000,PO,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4688,68c1ec59f30a816cfad1d5a3,4691,700B-547,35,ACCESORIOS FUMIGACION,BANDA DAYCO 15410,16,VARIOS BOMBAS,,6.087,6.087,9.0000,9.450,10.0000,PO,True,False
4689,68c1ec59f30a816cfad1d5a4,4714,700B-112,35,ACCESORIOS FUMIGACION,POLEA 12 X 2 RANURAS TORNEADO,16,VARIOS BOMBAS,,19.560,19.560,38.0000,39.000,40.9500,PO,True,False
4690,68c1ec59f30a816cfad1d5a5,4715,700B-111,35,ACCESORIOS FUMIGACION,POLEA 11 X 2 RANURAS TORNEADA,16,VARIOS BOMBAS,,18.260,18.260,33.7500,35.500,37.3000,PO,True,False
4691,68c1ec59f30a816cfad1d5a6,4756,308-0014SI,35,ACCESORIOS FUMIGACION,ACORDEON MD8026,7,MARUYAMA,,11.520,11.520,16.4000,17.250,18.1100,PO,False,False
4692,68c1ec59f30a816cfad1d5a7,4764,700B-280,35,ACCESORIOS FUMIGACION,FLAUTA SALIDAS BOMBA DE FUMIGAR,16,VARIOS BOMBAS,,40.000,41.250,0.0000,0.000,0.0000,PO,False,False

In [ ]:
df_products = df_products[["product_id","product_code", "product_name", "category_name", "brand_name","price_cash", "is_spare_part"]]

### Discounted and New products

In [ ]:
rules_df = pd.read_csv("product_rules.csv")

# Step 2: Low-value and boost product flag
# -------------------
new_product_codes = rules_df.query("rule_type == 'code' and category == 'boost'")["rule_value"].tolist()

def new_product(row):
    code = row["product_code"]
    if code in new_product_codes:
        return True
    return False

df_products["new_product"] = df_products.apply(new_product, axis=1)

df_products['discount'] = 0

/var/folders/z_/f3rpfjgn6j1bwmghgxsm9nbm0000gn/T/ipykernel_77839/2493918737.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_products["new_product"] = df_products.apply(new_product, axis=1)
/var/folders/z_/f3rpfjgn6j1bwmghgxsm9nbm0000gn/T/ipykernel_77839/2493918737.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_products['discount'] = 0

In [39]:
df_products[df_products["new_product"] == True]

,product_id,product_code,product_name,category_name,brand_name,price_cash,new_product,discount
4201,1155,408-0009SI,MOTOCULTOR TF545DE ARRANQUE ELECTRICO,MOTOCULTORES,HUSQVARNA,2300.0,True,0

In [40]:
df_products.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4693 entries, 0 to 4692
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   product_id     4693 non-null   int64
 1   product_code   4693 non-null   object
 2   product_name   4693 non-null   object
 3   category_name  4693 non-null   object
 4   brand_name     4693 non-null   object
 5   price_cash     4693 non-null   float64
 6   new_product    4693 non-null   bool
 7   discount       4693 non-null   int64
dtypes: bool(1), float64(1), int64(2), object(4)
memory usage: 261.4+ KB

# IMAGE LINKS

In [42]:
# Select the database and collection
cm_env = os.environ.get('CM_ENV', 'dev')
if cm_env == 'prod':
    collection = client["campomaq"]["cm_images"]
else:
    collection = client["campomaq_test"]["cm_images"]

# Read all documents from the collection
cursor = collection.find({})
df_product_images = pd.DataFrame(list(cursor))

In [43]:
df_product_images = df_product_images[['product_id','link']]
df_product_images

      product_id                                               link
0             10  [https://campomaq.blob.core.windows.net/campom...
1             14  [https://campomaq.blob.core.windows.net/campom...
2             19  [https://campomaq.blob.core.windows.net/campom...
3             20  [https://campomaq.blob.core.windows.net/campom...
4             21  [https://campomaq.blob.core.windows.net/campom...
...          ...                                                ...
2372        4189  [https://campomaq.blob.core.windows.net/campom...
2373        4192  [https://campomaq.blob.core.windows.net/campom...
2374        4193  [https://campomaq.blob.core.windows.net/campom...
2375        4232  [https://campomaq.blob.core.windows.net/campom...
2376        4233  [https://campomaq.blob.core.windows.net/campom...

[2377 rows x 2 columns]

In [44]:
# 2. Join products with images on product_id
prod_img_df = df_products.merge(df_product_images, on="product_id", how="left")

# 3. Join with popularity_df on product_code df_top_sales_prods
final_df = prod_img_df.merge(df_top_sales_prods, on="product_code", how="left")

In [45]:
final_df

,product_id,product_code,product_name,category_name,brand_name,price_cash,new_product,discount,link,main_boost,low_value_flag,popularity
0,0,0,.,SIN CATEGORIA,S.M.,0.0000,False,0,NaN,NaN,NaN,NaN
1,3368,700M-024,GATO HIDRAULICO TIPO BOTELLA,SIN CATEGORIA,VARIOS MOTORES,111.1525,False,0,NaN,NaN,NaN,NaN
2,4167,700M-121,TIJERA T-55C COSECHA Y PODA,SIN CATEGORIA,VARIOS MOTORES,0.0000,False,0,NaN,0.0,0.0,0.000583
3,1,101-0066SI,"DESBROZADOR FS-450/ CUCHILLA, VISERA COMPLETA,...",MOTOGUADANAS,STIHL,902.9126,False,0,NaN,NaN,NaN,NaN
4,803,305-0106SI,DESBROZADORA B50R RIGIDA MARUYAMA,MOTOGUADANAS,MARUYAMA,776.6990,False,0,[https://campomaq.blob.core.windows.net/campom...,0.0,0.0,0.009280
...,...,...,...,...,...,...,...,...,...,...,...,...
4688,4691,700B-547,BANDA DAYCO 15410,ACCESORIOS FUMIGACION,VARIOS BOMBAS,9.0000,False,0,NaN,NaN,NaN,NaN
4689,4714,700B-112,POLEA 12 X 2 RANURAS TORNEADO,ACCESORIOS FUMIGACION,VARIOS BOMBAS,38.0000,False,0,NaN,0.0,0.0,0.000741
4690,4715,700B-111,POLEA 11 X 2 RANURAS TORNEADA,ACCESORIOS FUMIGACION,VARIOS BOMBAS,33.7500,False,0,NaN,0.0,0.0,0.000150
4691,4756,308-0014SI,ACORDEON MD8026,ACCESORIOS FUMIGACION,MARUYAMA,16.4000,False,0,NaN,0.0,0.0,0.000101
4692,4764,700B-280,FLAUTA SALIDAS BOMBA DE FUMIGAR,ACCESORIOS FUMIGACION,VARIOS BOMBAS,0.0000,False,0,NaN,1.0,0.0,0.200908

# OTHER VARIABLES

In [47]:
final_df['brand_logo'] = '/images/brands/placeholder.png'

# PRODUCT DESCRIPTION

In [46]:
import openai
from openai import OpenAI
from dotenv import load_dotenv, find_dotenv
from tqdm import tqdm
import math
import json
from concurrent.futures import ThreadPoolExecutor, as_completed


# Load environment variables
load_dotenv(find_dotenv())
tqdm.pandas()

openai.api_key = os.environ['OPENAI_API_KEY']
# Initialize client
client = OpenAI()


# Function to process one batch
def process_batch(i, batch, num_batches):
    prompt = "Write concise, bright and appealing product descriptions in spanish for an agricultural machinery e-commerce site.\n\n"
    for idx, row in batch.iterrows():
        prompt += f"Product {idx}:\n"
        prompt += f"Name: {row['product_name']}\n"
        prompt += f"Category: {row['category_name']}\n"
        prompt += f"Brand: {row['brand_name']}\n\n"
    prompt += "Return the results as JSON with keys being the product index and values being the description."

    response = client.chat.completions.create(
        model="gpt-5-nano",  # you can switch model here
        messages=[{"role": "user", "content": prompt}],
        # temperature=0.7
    )

    try:
        batch_desc = json.loads(response.choices[0].message.content)
    except Exception as e:
        print(f"⚠️ JSON parsing failed in batch {i}: {e}")
        batch_desc = {str(idx): response.choices[0].message.content for idx in batch.index}

    # 👀 Print one sample from this batch
    sample_idx = next(iter(batch.index))
    print(f"\nBatch {i+1}/{num_batches} sample → {batch_desc.get(str(sample_idx), '')[:150]}...\n")

    return batch_desc

# Main function
def generate_descriptions_multithread(df, batch_size=20, max_workers=5):
    descriptions = {}
    num_batches = math.ceil(len(df) / batch_size)

    with ThreadPoolExecutor(max_workers=max_workers) as executor:
        futures = []
        for i in range(num_batches):
            batch = df.iloc[i*batch_size:(i+1)*batch_size]
            futures.append(executor.submit(process_batch, i, batch, num_batches))

        for future in tqdm(as_completed(futures), total=len(futures), desc="Generating descriptions"):
            batch_desc = future.result()
            for k, v in batch_desc.items():
                descriptions[int(k)] = v

    return [descriptions[idx] for idx in df.index]

# Run with multithreading
final_df["description"] = generate_descriptions_multithread(final_df, batch_size=20, max_workers=5)

Generating descriptions:   0%|          | 1/235 [00:25<1:40:57, 25.89s/it]

Batch 4/235 sample → Aceite 2T MARUYAMA 1L: lubricante de alto rendimiento para motores de dos tiempos; mezcla fácil y protección óptima para la motosierra....

Generating descriptions:   1%|          | 2/235 [00:28<47:11, 12.15s/it]

Batch 5/235 sample → Empaque de cilindro STIHL 051: repuesto original para motosierras, garantiza sellado perfecto y rendimiento duradero....

Generating descriptions:   1%|▏         | 3/235 [00:32<32:09,  8.32s/it]

Batch 1/235 sample → S.M. presenta un producto versátil y confiable: ideal para múltiples tareas en el campo....

Generating descriptions:   2%|▏         | 4/235 [00:34<22:17,  5.79s/it]

Batch 2/235 sample → Cortasetos 525HE4 de Husqvarna: precisión y potencia para setos exigentes, cuchillas afiladas y manejo ergonómico para un acabado profesional....

Generating descriptions:   2%|▏         | 5/235 [00:39<21:51,  5.70s/it]

Batch 3/235 sample → DIENTES DE CADENA 660/051/076 – STIHL. Dientes de cadena de alto rendimiento para motosierras STIHL, compatibles con los modelos 660/051/076; precisió...

Generating descriptions:   3%|▎         | 6/235 [00:49<26:40,  6.99s/it]

Batch 7/235 sample → Arrancador retráctil 380 STIHL: arranque rápido y fiable para tus motosierras....

Generating descriptions:   3%|▎         | 7/235 [00:50<19:43,  5.19s/it]

Batch 8/235 sample → Junta de cilindro para FS250: sellado perfecto y rendimiento duradero con repuestos originales STIHL....

Generating descriptions:   3%|▎         | 8/235 [00:52<15:17,  4.04s/it]

Batch 6/235 sample → Garra de tope 051/076 – repuesto original STIHL para motosierras. Duradera y precisa, garantiza seguridad y rendimiento confiable en cada corte....

Generating descriptions:   4%|▍         | 9/235 [00:56<15:42,  4.17s/it]

Batch 9/235 sample → Tensor de cadena CPL para motosierra STIHL MS-250. Mantiene la tensión perfecta de la cadena para cortes suaves y eficientes. Instalación rápida y de ...

Generating descriptions:   4%|▍         | 10/235 [01:01<16:12,  4.32s/it]

Batch 10/235 sample → Conjunto de engranaje y tornillo tensor para MS-038/MS-380/MS-660. Asegura la tensión de la cadena y un rendimiento duradero de STIHL....

Generating descriptions:   5%|▍         | 11/235 [01:04<14:45,  3.95s/it]

Batch 11/235 sample → Chapa lateral interior compatible con STIHL 051/076. Repuesto original para ajuste perfecto, durabilidad y seguridad en tu motosierra....

Generating descriptions:   5%|▌         | 12/235 [01:05<11:55,  3.21s/it]

Batch 12/235 sample → Aguja de admisión grande compatible con 051/076/381/660. Repuesto original STIHL para arranques suaves y rendimiento estable....

Generating descriptions:   6%|▌         | 13/235 [01:08<11:11,  3.02s/it]

Batch 13/235 sample → Retén 14x20x3.5 para motosierras MS660. Repuesto STIHL de alta durabilidad, para un sellado fiable y rendimiento continuo....

Generating descriptions:   6%|▌         | 14/235 [01:18<18:24,  5.00s/it]

Batch 14/235 sample → Conjunto de retenedores de alta durabilidad para STIHL MS380/038, fiabilidad y rendimiento duradero....

Generating descriptions:   6%|▋         | 15/235 [01:24<19:39,  5.36s/it]

Batch 16/235 sample → Retén izquierdo de cigüeñal compatible con Husqvarna 365 (cód. 577-32-49-01). Repuesto original Husqvarna, duradero y de ajuste perfecto para evitar f...

Generating descriptions:   7%|▋         | 16/235 [01:25<15:01,  4.11s/it]

Batch 15/235 sample → Perno silenciador y mango delantero para motosierras Husqvarna (modelos 225, 250, 241R, 325PX, 268, 288, 365, 394, 395, 2101). Repuesto original, dura...

Generating descriptions:   7%|▋         | 17/235 [01:30<15:42,  4.32s/it]

Batch 17/235 sample → Resorte de embrague para motosierras Husqvarna (modelos 268, 272 y 380). Repuesto original que garantiza un embrague suave y fiable....

Generating descriptions:   8%|▊         | 18/235 [01:33<14:16,  3.95s/it]

Batch 18/235 sample → Tambor embrague 3/8x7 (61.268.272). Repuesto original Husqvarna para motosierras; duradero y fácil de instalar para una entrega de potencia confiable....

Generating descriptions:   8%|▊         | 19/235 [01:36<12:47,  3.55s/it]

Batch 19/235 sample → Polea de arranque original para Husqvarna 394/395. Repuesto duradero y fiable para arranques suaves en trabajo diario....

Generating descriptions:   9%|▊         | 20/235 [01:38<11:45,  3.28s/it]

Batch 21/235 sample → Perno 288 para motosierra Husqvarna: repuesto original, alto rendimiento y resistencia para reparaciones rápidas....

Generating descriptions:   9%|▉         | 21/235 [01:50<20:31,  5.76s/it]

Batch 20/235 sample → Templador de cadena para motosierra Husqvarna, compatible con modelos CPL 268, 272 y 288. Aporta precisión en el ajuste de la cadena y durabilidad par...

Generating descriptions:   9%|▉         | 22/235 [01:51<15:56,  4.49s/it]

Batch 23/235 sample → TAPA CUBIERTA DE CADENA 390XP. Repuesto original Husqvarna que protege la cadena y mantiene la motosierra segura y eficiente....

Generating descriptions:  10%|▉         | 23/235 [01:55<14:54,  4.22s/it]

Batch 24/235 sample → Brida de carburador para Husqvarna 394. Repuesto de alta resistencia que garantiza ajuste preciso y rendimiento óptimo....

Generating descriptions:  10%|█         | 24/235 [01:59<15:16,  4.35s/it]

Batch 22/235 sample → PISTON CPL 395 48MM — Husqvarna. Repuesto completo para motosierras; precisión y durabilidad para recuperar la potencia del modelo 395....

Generating descriptions:  11%|█         | 25/235 [02:06<17:37,  5.04s/it]

Batch 25/235 sample → ARANDELA DE TAMBOR DE EMBRAGUE 365 - Repuesto original Husqvarna para motosierras: duradera y fiable para un embrague suave....

Generating descriptions:  11%|█         | 26/235 [02:11<17:52,  5.13s/it]

Batch 26/235 sample → Juego de empaques WALB para Husqvarna (modelos M61, 390, 395, 288 y 660). Repuestos de alta durabilidad para un mantenimiento confiable de tu motosier...

Generating descriptions:  11%|█▏        | 27/235 [02:12<13:21,  3.86s/it]

Batch 27/235 sample → Filtro de aire TR530 para motosierras Husqvarna. Protege el motor y mantiene un rendimiento óptimo....

Generating descriptions:  12%|█▏        | 28/235 [02:15<11:52,  3.44s/it]

Batch 28/235 sample → Pinón 3/8 B19091: repuesto confiable para motosierras. Mejora la tracción de la cadena y garantiza cortes precisos. Compatibilidad con VARIOS MOTORES....

Generating descriptions:  12%|█▏        | 29/235 [02:18<11:22,  3.32s/it]

Batch 29/235 sample → SILENCIADOR MS-250 para motosierras STIHL: reduce el ruido y mantiene la potencia y la durabilidad....

Generating descriptions:  13%|█▎        | 30/235 [02:31<21:37,  6.33s/it]

Batch 31/235 sample → Pistón completo de alta durabilidad para motosierra 288, ajuste perfecto y rendimiento confiable, de HUSQVARNA....

Generating descriptions:  13%|█▎        | 31/235 [02:33<17:02,  5.01s/it]

Batch 30/235 sample → Filtro de aire MS-310 de STIHL: filtración eficiente para proteger el motor y mantener un rendimiento óptimo....

Generating descriptions:  14%|█▎        | 32/235 [02:39<17:28,  5.16s/it]

Batch 33/235 sample → Bomba de fumigar manual de 5 litros, ligera y fácil de usar para proteger tus cultivos....

Generating descriptions:  14%|█▍        | 33/235 [02:41<14:59,  4.45s/it]

Batch 34/235 sample → Bomba de fumigar AR50 con motor trifásico 7.5HP, 5 salidas completo. Potencia y rendimiento para fumigaciones de gran escala; distribución uniforme y ...

Generating descriptions:  14%|█▍        | 34/235 [02:49<17:37,  5.26s/it]

Batch 32/235 sample → Cilindro completo para motosierras STIHL 050/051/TS510 (ALT). Repuesto original, alto rendimiento y ajuste perfecto....

Generating descriptions:  15%|█▍        | 35/235 [02:53<16:18,  4.89s/it]

Batch 35/235 sample → Casquillo cuadrado en U para FS280/450, repuesto STIHL: precisión y durabilidad para un rendimiento fiable....

Generating descriptions:  15%|█▌        | 36/235 [02:57<16:08,  4.87s/it]

Batch 36/235 sample → Cabeza de nylon para STIHL 450/280 en acción manual. Repuesto original, instalación rápida y durabilidad superior para trabajos de siega intensos....

Generating descriptions:  16%|█▌        | 37/235 [03:01<15:01,  4.55s/it]

Batch 38/235 sample → Tuerca hexagonal M5 de ajuste de carburador para STIHL FS450. Repuesto original, montaje rápido y ajuste preciso....

Generating descriptions:  16%|█▌        | 38/235 [03:03<12:28,  3.80s/it]

Batch 37/235 sample → Repuesto robusto de STIHL para motoguadañas: cierre de depósito BG86 que garantiza sellado seguro y rendimiento duradero....

Generating descriptions:  17%|█▋        | 39/235 [03:14<19:28,  5.96s/it]

Batch 41/235 sample → Aguja de admisión original STIHL para FS450 y modelos compatibles (Maruyama BC420, 160STH); ajuste preciso y rendimiento fiable....

Generating descriptions:  17%|█▋        | 40/235 [03:22<21:27,  6.60s/it]

Batch 39/235 sample → JUEGO PIEZAS CARBURADOR FS280 — Repuestos STIHL para motoguadañas. Mantén tu FS280 al máximo rendimiento con piezas de calidad....

Generating descriptions:  17%|█▋        | 41/235 [03:29<21:19,  6.60s/it]

Batch 43/235 sample → Repuesto de pistón para motores MARUYAMA BF43R/4320/420/500. Asegura ajuste preciso y rendimiento duradero....

Generating descriptions:  18%|█▊        | 42/235 [03:38<23:35,  7.34s/it]

Batch 42/235 sample → JUEGO EMPAQUEMOTOR 753T - Repuesto original Oleomac para motoguadañas. Sellos y juntas de alta duración para rendimiento confiable....

Generating descriptions:  18%|█▊        | 43/235 [03:39<17:29,  5.46s/it]

Batch 44/235 sample → Engranaje angular de 10 mm para motoguadañas MARUYAMA, compatible con BF43/B43/50R/BC420/BCF4321H. Precisión y durabilidad para un rendimiento fiable....

Generating descriptions:  19%|█▊        | 44/235 [03:42<14:49,  4.65s/it]

Batch 40/235 sample → Abrazadera de sujeción brida 32x5 para FS-280. Pieza resistente que garantiza un ajuste seguro en motoguadañas STIHL....

Generating descriptions:  19%|█▉        | 45/235 [03:43<11:30,  3.63s/it]

Batch 45/235 sample → Perno de carcaza de alta resistencia para BC420 y B43, MARUYAMA. Fija con fiabilidad la transmisión de tu motoguadaña....

Generating descriptions:  20%|█▉        | 46/235 [03:54<18:13,  5.78s/it]

Batch 46/235 sample → Deflector de calor para MARUYAMA BC4320H/B50R: protege el motor, reduce la temperatura de operación y mejora la durabilidad de la motoguadaña....

Generating descriptions:  20%|██        | 47/235 [04:02<20:36,  6.58s/it]

Batch 47/235 sample → Cuerda de arranque resistente para BF43/50, repuesto MARUYAMA. Arranque suave y fiable para tu motoguadaña....

Generating descriptions:  20%|██        | 48/235 [04:07<18:56,  6.08s/it]

Batch 50/235 sample → Rodamiento de agujas de alta precisión para Husqvarna 143RII. Reduce la fricción, mejora la suavidad de giro y prolonga la vida útil del tren de trans...

Generating descriptions:  21%|██        | 49/235 [04:10<15:39,  5.05s/it]

Batch 48/235 sample → Kit de empaques para carburador MARUYAMA, compatible con 420/500/142R/143RII/4320/753/743 ALT. Incluye juntas y sellos para un sellado fiable y montaj...

Generating descriptions:  21%|██▏       | 50/235 [04:11<11:29,  3.73s/it]

Batch 49/235 sample → CUBIERTA DE CILINDRO CPL 142R 143RI - Repuesto original HUSQVARNA para motoguadañas, ajuste perfecto y duradero....

Generating descriptions:  22%|██▏       | 51/235 [04:16<13:16,  4.33s/it]

Batch 51/235 sample → Escape para motoguadaña Husqvarna 143RII: silenciador duradero y rendimiento óptimo....

Generating descriptions:  22%|██▏       | 52/235 [04:20<12:23,  4.06s/it]

Batch 52/235 sample → Empaque de brida para 143RII/236R, repuesto original Husqvarna que garantiza sellado confiable y rendimiento duradero....

Generating descriptions:  23%|██▎       | 53/235 [04:30<17:41,  5.83s/it]

Batch 54/235 sample → Polea de arranque 133R, Husqvarna — repuesto resistente para motoguadañas, arranques suaves y fiables....

Generating descriptions:  23%|██▎       | 54/235 [04:31<13:45,  4.56s/it]

Batch 53/235 sample → Empaque de brida para cilindro 142R. Repuesto original Husqvarna para un sellado perfecto y rendimiento confiable....

Generating descriptions:  23%|██▎       | 55/235 [04:33<10:57,  3.65s/it]

Batch 55/235 sample → Soporte base resistente para la motoguadaña Husqvarna 226R. Fijación estable y montaje sencillo para un rendimiento duradero en tus trabajos de siega....

Generating descriptions:  24%|██▍       | 56/235 [04:43<17:04,  5.72s/it]

Batch 57/235 sample → Amortiguador pequeño de repuesto para motoguadañas Husqvarna, compatible con 236R y 143RII. Absorbe impactos y mejora la durabilidad....

Generating descriptions:  24%|██▍       | 57/235 [04:44<12:44,  4.29s/it]

Batch 56/235 sample → Filtro de combustible Husqvarna 226R-143RII. Repuesto original que protege el sistema de combustible y mejora el rendimiento de tu motoguadaña....

Generating descriptions:  25%|██▍       | 58/235 [04:53<16:22,  5.55s/it]

Batch 58/235 sample → CARBURADOR CPL 143RII 226R 325S25 - HUSQVARNA. Repuesto de alto rendimiento para motoguadañas, con arranque suave y fiabilidad....

Generating descriptions:  25%|██▌       | 59/235 [04:56<14:02,  4.79s/it]

Batch 59/235 sample → Repuesto original Husqvarna para la caja de piñones 327HE4X. Durabilidad y rendimiento confiable para la transmisión de tu motoguadaña....

Generating descriptions:  26%|██▌       | 60/235 [04:58<11:57,  4.10s/it]

Batch 60/235 sample → PIN DE PISTON MARUYAMA para BF43R/50/4320: precisión, durabilidad y ajuste perfecto para tu motoguadaña....

Generating descriptions:  26%|██▌       | 61/235 [05:02<11:53,  4.10s/it]

Batch 62/235 sample → Kit de cilindro y pistón para guadaña. Repuesto de alto rendimiento de VARIOS MOTORES, para uso rudo y larga vida....

Generating descriptions:  26%|██▋       | 62/235 [05:06<11:02,  3.83s/it]

Batch 61/235 sample → Kit trinquete para motoguadaña, compatible con múltiples motores VARIOS MOTORES. Construcción robusta para un desbroce eficiente y duradero....

Generating descriptions:  27%|██▋       | 63/235 [05:13<14:22,  5.01s/it]

Batch 63/235 sample → Empaque de Cilindro SHINDAIHUA para motoguadaña: repuesto de alta durabilidad que garantiza un sellado eficiente y rendimiento óptimo....

Generating descriptions:  27%|██▋       | 64/235 [05:18<13:45,  4.83s/it]

Batch 64/235 sample → Cubierta de cilindro para MARUYAMA BC422/BCF420. Protege la compresión y ofrece ajuste preciso para un rendimiento estable....

Generating descriptions:  28%|██▊       | 65/235 [05:21<12:05,  4.27s/it]

Batch 66/235 sample → Escape para guadaña de origen chino, compatible con múltiples motoguadañas. Rendimiento fiable y fácil instalación....

Generating descriptions:  28%|██▊       | 66/235 [05:23<10:04,  3.58s/it]

Batch 65/235 sample → Valvula V.R.P completa MS330-331 para motoguadañas MARUYAMA. Repuesto confiable para rendimiento óptimo y instalación rápida....

Generating descriptions:  29%|██▊       | 67/235 [05:26<09:47,  3.50s/it]

Batch 67/235 sample → Campana de embrague CPL DBC3300M - repuesto Ducatti, rendimiento fiable y duradero....

Generating descriptions:  29%|██▉       | 68/235 [05:28<08:41,  3.12s/it]

Batch 68/235 sample → Empuñadura de mando para motoguadañas STIHL FS-490/FS-510/FS560. Repuesto ergonómico y duradero para control total y mayor comodidad en cada pasada....

Generating descriptions:  29%|██▉       | 69/235 [05:42<17:20,  6.27s/it]

Batch 69/235 sample → Cuchilla de repuesto para cortasetos STIHL 131R, 500 mm (20\"). Afilada, duradera y diseñada para cortes limpios....

Generating descriptions:  30%|██▉       | 70/235 [05:44<13:49,  5.03s/it]

Batch 70/235 sample → Bastidor/Manillar MS-170 para motoguadañas STIHL: repuesto robusto y ergonómico que mejora el control y la durabilidad en cada trabajo....

Generating descriptions:  30%|███       | 71/235 [05:45<10:12,  3.74s/it]

Batch 72/235 sample → Repuesto original STIHL para BG50. Carburador que garantiza rendimiento fiable, arranque suave y mayor eficiencia en tareas de soplado....

Generating descriptions:  31%|███       | 72/235 [05:46<07:42,  2.84s/it]

Batch 71/235 sample → Abrazadera de mango completa para BF43/B50R/BCF420H/420 de MARUYAMA. Repuesto resistente para motoguadañas, garantiza un agarre seguro y reparación rá...

Generating descriptions:  31%|███       | 73/235 [05:47<06:42,  2.49s/it]

Batch 73/235 sample → Silenciador original STIHL para motoguadaña FS85. Reduce el ruido y mejora la eficiencia en tus trabajos agrícolas....

Generating descriptions:  31%|███▏      | 74/235 [05:58<13:31,  5.04s/it]

Batch 76/235 sample → Anillo de pistón de alta resistencia compatible con HC-152, HC-150 y SRM-225U. Excelente sellado y durabilidad para un rendimiento confiable en cada t...

Generating descriptions:  32%|███▏      | 75/235 [06:03<12:58,  4.87s/it]

Batch 78/235 sample → Pistón Hoyadora SHINDAIHUA DEA5200/DBC5201T. Repuesto de alta precisión para un rendimiento óptimo y durabilidad....

Generating descriptions:  32%|███▏      | 76/235 [06:05<10:41,  4.04s/it]

Batch 77/235 sample → Cilindro 365XO para motoguadañas Husqvarna. Repuesto original de alto rendimiento, precisión y durabilidad para tus trabajos de poda....

Generating descriptions:  33%|███▎      | 77/235 [06:06<08:33,  3.25s/it]

Batch 74/235 sample → Jaula de agujas 8x11x10 para KM85R (STIHL). Repuesto original para un giro suave y duradero de tu motoguadaña....

Generating descriptions:  33%|███▎      | 78/235 [06:10<08:40,  3.31s/it]

Batch 75/235 sample → JUEGO DE JUNTAS HS82T CORTASETOS — Repuesto original STIHL para HS82T. Sellos de alta precisión para un rendimiento fiable....

Generating descriptions:  34%|███▎      | 79/235 [06:20<14:18,  5.50s/it]

Batch 79/235 sample → Resorte de tracción original para carburador FS460. Repuestos motoguadanas STIHL. Arranque suave y rendimiento confiable para tus herramientas....

Generating descriptions:  34%|███▍      | 80/235 [06:27<15:16,  5.91s/it]

Batch 83/235 sample → Tornillo templador para Motosierra 394/395 de HUSQVARNA. Repuesto original de alta resistencia que garantiza un tensionado preciso y rendimiento fiabl...

Generating descriptions:  34%|███▍      | 81/235 [06:27<10:49,  4.22s/it]

Batch 81/235 sample → Palanca de acelerador completa para SHINDAIHUA B450/B530: control suave y respuesta rápida para tus trabajos en campo....

Generating descriptions:  35%|███▍      | 82/235 [06:35<13:08,  5.15s/it]

Batch 82/235 sample → Volante de arranque para multicutter Ducattu DBC3301MS. Repuesto robusto y de instalación rápida, compatible con motores de múltiples marcas para un a...

Generating descriptions:  35%|███▌      | 83/235 [06:37<10:39,  4.21s/it]

Batch 80/235 sample → EMPUÑADURA CPL BCV5020 CON CABLE ACELERADOR de MARUYAMA. Repuesto ergonómico para motoguadañas que mejora el agarre y el control del acelerador, aumen...

Generating descriptions:  36%|███▌      | 84/235 [06:43<12:23,  4.92s/it]

Batch 84/235 sample → Motosierra STIHL MS 361 con espada de 50 cm y cadena 3/8: potencia fiable para trabajos difíciles....

Generating descriptions:  36%|███▌      | 85/235 [06:56<18:05,  7.23s/it]

Batch 85/235 sample → Set de reparación automotriz 6 piezas: herramientas esenciales para mantenimiento rápido en finca o taller....

Generating descriptions:  37%|███▋      | 86/235 [07:00<15:17,  6.16s/it]

Batch 86/235 sample → Disco diamante segmentado de 7 pulgadas (180x22 mm) para baldosas, mampostería y hormigón. Corte rápido y limpio. Neo DS10180 - FORESTA GARDEN....

Generating descriptions:  37%|███▋      | 87/235 [07:05<14:16,  5.79s/it]

Batch 88/235 sample → Hidrolavadora industrial Porten 5HP (PHI5MC): potencia y rendimiento para limpieza intensiva de maquinaria y áreas agrícolas; construcción robusta y f...

Generating descriptions:  37%|███▋      | 88/235 [07:13<15:58,  6.52s/it]

Batch 87/235 sample → MANGUERA DE FUMIGACIÓN 8.5 mm, color amarillo; flexible y resistente, perfecta para aplicar pesticidas y fertilizantes en cultivos....

Generating descriptions:  38%|███▊      | 89/235 [07:16<13:27,  5.53s/it]

Batch 89/235 sample → Compresor Campbell CH, 2 HP, tanque de 50 L y 3.2 CFM; modelo CHDC5001, fiable para herramientas neumáticas en granjas....

Generating descriptions:  38%|███▊      | 90/235 [07:19<11:47,  4.88s/it]

Batch 90/235 sample → Taladro percutor 1/2 pulg. con velocidad variable, compacto y confiable para perforaciones rápidas en el campo....

Generating descriptions:  39%|███▊      | 91/235 [07:26<12:49,  5.34s/it]

Batch 91/235 sample → Pinza porta electrodo de 300 A: sujeción firme y fiable para soldar en campo o taller (VARIOS MOTORES)....

Generating descriptions:  39%|███▉      | 92/235 [07:28<10:23,  4.36s/it]

Batch 92/235 sample → Cuchilla Tijera Goodyear GY2802S: filo afilado para cortes precisos y rápidos en poda....

Generating descriptions:  40%|███▉      | 93/235 [07:41<16:22,  6.92s/it]

Batch 94/235 sample → Hoyadora Goodyear GY052EA 51.7cc: potente, fiable y ergonómica para perforaciones en el campo....

Generating descriptions:  40%|████      | 94/235 [07:45<14:13,  6.05s/it]

Batch 95/235 sample → Aireación de depósito BG86/381 - Repuesto STIHL para optimizar la aireación del depósito y garantizar una fumigación eficiente....

Generating descriptions:  40%|████      | 95/235 [07:46<10:29,  4.50s/it]

Batch 93/235 sample → Pistola/Lanzadera de alta presión 4000 PSI, PHI-4M (23065), modelo PORTEN. Ideal para lavado y desinfección en campo, rendimiento confiable....

Generating descriptions:  41%|████      | 96/235 [07:57<14:57,  6.46s/it]

Batch 97/235 sample → O-ring de repuesto para la tapa cigüeñal AR-30. Sello hermético y duradero para un rendimiento fiable en fumigación ANNOVI REVERVERI....

Generating descriptions:  41%|████▏     | 97/235 [08:03<14:36,  6.35s/it]

Batch 96/235 sample → Bloque de bomba AR/30, repuesto robusto para fumigación, rendimiento fiable de ANNOVI REVERVERI....

Generating descriptions:  42%|████▏     | 98/235 [08:07<13:12,  5.78s/it]

Batch 98/235 sample → Seguro del pistón para AR-30, resistente y preciso, diseñado por ANNOVI REVERVERI para repuestos de fumigación....

Generating descriptions:  42%|████▏     | 99/235 [08:09<10:10,  4.49s/it]

Batch 100/235 sample → Semicámara inferior metálica AR50, repuesto de ANNOVI REVERVERI para fumigación, duradero y resistente a químicos....

Generating descriptions:  43%|████▎     | 100/235 [08:20<15:03,  6.69s/it]

Batch 99/235 sample → Biela AR-50 de alta resistencia para un rendimiento suave y duradero en la fumigación, compatible con AR-50 de ANNOVI REVERVERI....

Generating descriptions:  43%|████▎     | 101/235 [08:27<14:40,  6.57s/it]

Batch 104/235 sample → O-ring en asiento de esfera para sellado de precisión en equipos MARUYAMA; compatible con MS 653/253; resistente a químicos y presión....

Generating descriptions:  43%|████▎     | 102/235 [08:29<11:27,  5.17s/it]

Batch 101/235 sample → MARUYAMA MANGUERA DE RETORNO MS330/MSD41: resistente y flexible para sistemas de fumigación....

Generating descriptions:  44%|████▍     | 103/235 [08:29<08:07,  3.69s/it]

Batch 102/235 sample → Empaque de pistón MARUYAMA 055-056-068-073. Repuesto clave para una presión estable y rendimiento fiable en tus fumigaciones....

Generating descriptions:  44%|████▍     | 104/235 [08:37<11:14,  5.15s/it]

Batch 105/235 sample → Sello de agua para bomba MS331/330/253/653, MARUYAMA; repuesto de alta durabilidad para fumigación....

Generating descriptions:  45%|████▍     | 105/235 [08:42<10:41,  4.94s/it]

Batch 103/235 sample → ORING EN O MS330/3 - REPUESTOS FUMIGACION MARUYAMA: junta tórica de alto rendimiento para sellado perfecto y rendimiento estable....

Generating descriptions:  45%|████▌     | 106/235 [08:47<10:23,  4.84s/it]

Batch 106/235 sample → Tapa de aceite para bomba MS330/331, sellado duradero y confiable para equipos MARUYAMA de fumigación....

Generating descriptions:  46%|████▌     | 107/235 [08:49<08:38,  4.05s/it]

Batch 107/235 sample → Asiento de válvula de descarga MS055/056/068/073D, repuesto MARUYAMA para fumigación; precisión y durabilidad en tu equipo....

Generating descriptions:  46%|████▌     | 108/235 [09:06<17:02,  8.05s/it]

Batch 109/235 sample → Repuesto de fumigación Husqvarna: empaque de cilindro con brida Carb 362M18. Ajuste preciso y alta durabilidad para un rendimiento fiable....

Generating descriptions:  47%|████▋     | 110/235 [09:13<11:17,  5.42s/it]

Batch 110/235 sample → Kit bomba TS-22 (incompleto) POW: repuestos para la bomba de fumigación. Ideal para completar y volver a operar con fiabilidad POW....


Batch 111/235 sample → Kit de empaques para válvulas TS 30 de POW, repuesto para sistemas de fumigación. Sellado preciso que reduce fugas y alarga la vida útil de la válvula...

Generating descriptions:  47%|████▋     | 111/235 [09:13<08:01,  3.88s/it]

Batch 108/235 sample → EMPAQUE BASE CARBURADOR MD-150DX – Repuesto MARUYAMA para REPUESTOS FUMIGACION, ajuste preciso y durabilidad....

Generating descriptions:  48%|████▊     | 112/235 [09:21<10:25,  5.08s/it]

Batch 112/235 sample → PISTÓN CPL MITSUBIHSI-SUPERELY/ TROOPER — Repuesto POW para fumigación; rendimiento fiable y alta durabilidad....

Generating descriptions:  48%|████▊     | 113/235 [09:29<11:58,  5.89s/it]

Batch 113/235 sample → Rodamiento rígido 6309 NTN de BRIGS STRATON para repuestos de fumigación. Alto rendimiento, duradero y fiable para bombas y motores agrícolas....

Generating descriptions:  49%|████▊     | 114/235 [09:32<10:03,  4.99s/it]

Batch 116/235 sample → Filtro de aire SOLO para equipos de fumigación: máxima filtración, protege el motor y mejora el rendimiento....

Generating descriptions:  49%|████▉     | 115/235 [09:34<08:24,  4.20s/it]

Batch 115/235 sample → Unión de aspiración MD 423, repuesto de fumigación SOLO: conexión duradera y fiable para tu equipo agrícola....

Generating descriptions:  49%|████▉     | 116/235 [09:40<09:27,  4.77s/it]

Batch 114/235 sample → Bomba de fumigación manual de 2 L; fiable y fácil de usar para una fumigación eficiente en el campo....

Generating descriptions:  50%|████▉     | 117/235 [09:44<08:56,  4.54s/it]

Batch 117/235 sample → VALVULA VRP CPL 653/655 - Repuesto MARUYAMA para sistemas de fumigación. Precisión y durabilidad para un rendimiento fiable en campo....

Generating descriptions:  50%|█████     | 118/235 [09:52<10:33,  5.42s/it]

Batch 118/235 sample → Polea de bomba SB528-3052-428 de MARUYAMA. Repuesto confiable para sistemas de fumigación, con ajuste preciso y mayor durabilidad....

Generating descriptions:  51%|█████     | 119/235 [09:59<11:28,  5.94s/it]

Batch 120/235 sample → Bobina CIFARELLI (repuesto SOLO) para sistemas de fumigación. Fiable y de instalación rápida para mantener tu equipo en marcha....

Generating descriptions:  51%|█████     | 120/235 [10:03<10:03,  5.25s/it]

Batch 119/235 sample → Abrazadera de empuñadura AT900 CIFARELLI NUVOLA, repuesto SOLO para fumigación: ajuste seguro y montaje rápido....

Generating descriptions:  51%|█████▏    | 121/235 [10:10<11:19,  5.96s/it]

Batch 121/235 sample → CABLE DE ACELERACIÓN MD.23 SOLO: repuesto fiable para fumigación, precisión y durabilidad....

Generating descriptions:  52%|█████▏    | 122/235 [10:14<10:04,  5.35s/it]

Batch 123/235 sample → Nylon 2.0 mm redondo amarillo, 15 m. Línea de fumigación duradera y flexible para Husqvarna....

Generating descriptions:  52%|█████▏    | 123/235 [10:24<12:25,  6.66s/it]

Batch 122/235 sample → FILTRO DE AIRE COMPLETO MD423 SOLO: repuesto de alto rendimiento para fumigadoras SOLO; instalación rápida y mayor durabilidad....

Generating descriptions:  53%|█████▎    | 124/235 [10:32<13:08,  7.11s/it]

Batch 124/235 sample → Llave de 1/4 de pulgada con rosca interna: ajuste rápido y seguro para accesorios de fumigación....

Generating descriptions:  53%|█████▎    | 125/235 [10:38<12:28,  6.80s/it]

Batch 126/235 sample → Impulsor de bomba de 11.1 cm: potencia y rendimiento para fumigación eficiente....

Generating descriptions:  54%|█████▎    | 126/235 [10:54<17:14,  9.49s/it]

Batch 128/235 sample → Acople de manguera hembra de 2 pulgadas, tipo A. Conexión rápida y segura para fumigación. Marca VARIOS BOMBAS....

Generating descriptions:  54%|█████▍    | 127/235 [10:56<12:53,  7.16s/it]

Batch 127/235 sample → GIRELOS SIMPLES: accesorio de fumigación práctico y fiable para giros suaves. Marca VARIOS BOMBAS...

Generating descriptions:  54%|█████▍    | 128/235 [11:07<14:46,  8.29s/it]

Batch 129/235 sample → Filtro antigoteo para sistemas de fumigación. Evita derrames y mantiene la aplicación limpia; compatible con bombas VARIOS BOMBAS....

Generating descriptions:  55%|█████▍    | 129/235 [11:09<11:32,  6.53s/it]

Batch 125/235 sample → Conexión reductora 1/2 a 3/8 con rosca macho a macho, ideal para adaptar mangueras y equipos de fumigación, instalación rápida y segura....

Generating descriptions:  55%|█████▌    | 130/235 [11:13<10:07,  5.79s/it]

Batch 131/235 sample → BANDA A44 – Accesorio de fumigación compacto y resistente, diseñado para un rendimiento fiable en tus labores agrícolas....

Generating descriptions:  56%|█████▌    | 131/235 [11:18<09:47,  5.65s/it]

Batch 130/235 sample → Reductor plástico de 3/4 a 1/2: adaptador imprescindible para conectar conductos y optimizar el caudal en fumigaciones. Ligero, duradero y fácil de in...

Generating descriptions:  56%|█████▌    | 132/235 [11:36<15:55,  9.28s/it]

Batch 132/235 sample → Correa DAYCO 17510 de alta resistencia para fumigación. Duradera y de ajuste seguro para bombas VARIOS BOMBAS....

Generating descriptions:  57%|█████▋    | 133/235 [11:37<11:27,  6.74s/it]

Batch 134/235 sample → COLLARÍN PLÁSTICO NEGRO 25 MM a 1/2 pulgada - Accesorio de fumigación resistente y ligero, ideal para conectar mangueras con seguridad....

Generating descriptions:  57%|█████▋    | 134/235 [11:41<10:07,  6.02s/it]

Batch 135/235 sample → MANGUERA AMARILLO BICAPA 3/4 - Manguera bicapa amarilla de 3/4 para fumigación. Flexible, resistente a químicos y fácil de instalar; ideal para equipo...

Generating descriptions:  57%|█████▋    | 135/235 [11:43<07:43,  4.63s/it]

Batch 133/235 sample → ACOPLE REDUCTOR 1/2 pulgada a 1/4 pulgada: accesorio de fumigación para convertir roscas y facilitar conexiones. Marca VARIOS BOMBAS....

Generating descriptions:  58%|█████▊    | 136/235 [11:48<07:49,  4.74s/it]

Batch 136/235 sample → Banda A33 OPTIBELT para equipos de fumigación. Transmisión de alto rendimiento con ajuste preciso y larga vida útil para bombas VARIOS BOMBAS....

Generating descriptions:  58%|█████▊    | 137/235 [12:04<13:37,  8.34s/it]

Batch 138/235 sample → O-Ring para acople Foster: sellado fiable para fumigación. Compatible con bombas VARIOS BOMBAS; resistente a químicos....

Generating descriptions:  59%|█████▊    | 138/235 [12:17<15:38,  9.68s/it]

Batch 140/235 sample → Tuerca de 7/16 para accesorios de fumigación. Durable, de fácil fijación y compatible con VARIOS MOTORES....

Generating descriptions:  59%|█████▉    | 139/235 [12:19<11:39,  7.28s/it]

Batch 139/235 sample → Perno de 3/8 x 1 1/2 pulgadas con tuercas incluidas. Fijación segura y confiable para equipos de fumigación en maquinaria VARIOS MOTORES....

Generating descriptions:  60%|█████▉    | 140/235 [12:22<09:39,  6.10s/it]

Batch 137/235 sample → BANDA A20: banda de repuesto para sistemas de fumigación, resistente y de fácil ajuste. Garantiza un sellado seguro y un flujo estable....

Generating descriptions:  60%|██████    | 141/235 [12:33<11:55,  7.61s/it]

Batch 141/235 sample → BANDA DAYCO 17350 para sistemas de fumigación. Banda de alto rendimiento, duradera y de fácil instalación....

Generating descriptions:  60%|██████    | 142/235 [12:34<08:33,  5.52s/it]

Batch 142/235 sample → Arrancador 4.2HP Diésel TEMCO: repuesto fiable para motores 4T, fácil de instalar y arranque rápido para uso agrícola....

Generating descriptions:  61%|██████    | 143/235 [12:47<12:03,  7.86s/it]

Batch 145/235 sample → Kit de reparación de arranque 6.5HP a gasolina TEMCO para motores 4T. Repuestos de alta durabilidad que aseguran un arranque rápido y fiable....

Generating descriptions:  61%|██████▏   | 144/235 [12:52<10:19,  6.81s/it]

Batch 143/235 sample → Carburador TEMCO para motores 4T a gasolina, 13HP, repuesto fiable para un rendimiento óptimo....

Generating descriptions:  62%|██████▏   | 145/235 [12:57<09:42,  6.47s/it]

Batch 144/235 sample → Empaque de varilla para motor TEMCO 10HP Diésel. Repuesto 4T, duradero y confiable para sellos estables en maquinaria agrícola....

Generating descriptions:  62%|██████▏   | 146/235 [13:05<10:14,  6.91s/it]

Batch 146/235 sample → Escape de repuesto TEMCO para motores 4T de gasolina (13HP/9HP). Construcción robusta y ajuste perfecto para un rendimiento óptimo....

Generating descriptions:  63%|██████▎   | 147/235 [13:08<08:08,  5.56s/it]

Batch 147/235 sample → Juego de rines TEMCO para motores 13 HP a gasolina. Repuesto duradero, ajuste perfecto y rendimiento estable....

Generating descriptions:  63%|██████▎   | 149/235 [13:28<10:11,  7.11s/it]

Batch 150/235 sample → PALANCA GOBERNOR EY-20 de MARUYAMA. Repuesto para motores 4T a gasolina o diésel. Precisión y control suave para optimizar el rendimiento de su maquin...


Batch 149/235 sample → TAPA FILTRO AIRE para motores 10HP I/C. Protege la entrada de polvo y mejora el rendimiento de su equipo BRIGS STRATON....

Generating descriptions:  64%|██████▍   | 150/235 [13:29<07:23,  5.21s/it]

Batch 148/235 sample → CIGUEÑAL 192F CON ENGRANAJE - Repuesto TEMCO para motores 4T a gasolina o diésel. Durable, fiable y fácil de instalar....

Generating descriptions:  64%|██████▍   | 151/235 [13:39<09:13,  6.59s/it]

Batch 151/235 sample → Rodamiento 6305 NTN - BRIGS STRATON: alta durabilidad para motores 4T gasolina y diesel; precisión y fiabilidad para tu maquinaria agrícola....

Generating descriptions:  65%|██████▍   | 152/235 [13:51<11:25,  8.26s/it]

Batch 152/235 sample → Filtro de combustible BRIGS STRATON para motores 4T a gasolina y diésel. Filtra impurezas para proteger el sistema y mejorar el rendimiento....

Generating descriptions:  65%|██████▌   | 153/235 [13:54<08:59,  6.58s/it]

Batch 153/235 sample → Pistón STD 10HP I/C Especial con falda larga para motores 4T BRIGS STRATON....

Generating descriptions:  66%|██████▌   | 154/235 [13:57<07:22,  5.47s/it]

Batch 154/235 sample → Base filtro de aire para motor BRIGS STRATON 13.5 HP IC. Repuesto original que protege el motor y mantiene el rendimiento al máximo....

Generating descriptions:  66%|██████▌   | 155/235 [14:10<10:16,  7.71s/it]

Batch 155/235 sample → Pistón STD BRIGS STRATON, 6,5 HP, 68 mm. Repuesto confiable para motores 4T a gasolina y diésel; precisión y durabilidad para volver al trabajo....

Generating descriptions:  66%|██████▋   | 156/235 [14:20<11:00,  8.36s/it]

Batch 156/235 sample → Filtro de aire para motores 4T de 10 HP (gasolina/diésel). BRIGS STRATON. Protege el motor y mejora la eficiencia....

Generating descriptions:  67%|██████▋   | 157/235 [14:30<11:37,  8.94s/it]

Batch 159/235 sample → Filtro de aceite TEMCO para motores diésel de 10 HP. Repuesto 4T de confianza que protege el motor y prolonga la vida de su maquinaria agrícola....

Generating descriptions:  67%|██████▋   | 158/235 [14:36<10:25,  8.12s/it]

Batch 158/235 sample → Rin STD para motor Honda 9HP (4T). Fabricado por TEMCO: ajuste perfecto, durabilidad y rendimiento fiable para maquinaria agrícola....

Generating descriptions:  68%|██████▊   | 159/235 [14:39<08:19,  6.57s/it]

Batch 157/235 sample → Llave de paso para motor Robin, ideal para regular el flujo de combustible en motores 4T de gasolina y diésel. Repuesto TEMCO de alta durabilidad, ins...

Generating descriptions:  68%|██████▊   | 160/235 [14:57<12:18,  9.84s/it]

Batch 162/235 sample → Filtro de aire 11.5HP BRIGS STRATON ALT: repuesto esencial para motores 4T gasolina y diésel; mejora la admisión y protege el motor....

Generating descriptions:  69%|██████▊   | 161/235 [15:00<09:36,  7.80s/it]

Batch 161/235 sample → Válvula de admisión TKC450 corta (182) para motores 4T de gasolina y diésel. Mitsubishi: precisión y rendimiento confiables....

Generating descriptions:  69%|██████▉   | 162/235 [15:00<06:59,  5.75s/it]

Batch 160/235 sample → FILTRO DE AIRE ESPONJA 6.5HP HUECO – TEMCO. Repuesto para motores 4T de gasolina y diésel; esponja hueca que mejora el flujo de aire y facilita su lim...

Generating descriptions:  69%|██████▉   | 163/235 [15:05<06:25,  5.36s/it]

Batch 163/235 sample → Empaque del tubo de escape para motor 13HP TEMCO. Repuesto original para motores 4T a gasolina o diésel; ajuste preciso y sellado duradero....

Generating descriptions:  70%|██████▉   | 164/235 [15:22<10:27,  8.83s/it]

Batch 164/235 sample → Distribuidor para Generador ET950 de TEMCO. Repuesto original que garantiza chispa fiable y arranque estable, con montaje sencillo y durabilidad para ...

Generating descriptions:  70%|███████   | 165/235 [15:26<08:39,  7.42s/it]

Batch 168/235 sample → Cuchilla curva derecha para aporcar motocultor Ducatti DRTL2100. Precisión y durabilidad para tus labores....

Generating descriptions:  71%|███████   | 166/235 [15:33<08:19,  7.23s/it]

Batch 165/235 sample → Aceite 10W30 Motorex en galón para motores 4T a gasolina. Protección y rendimiento para jornadas intensas....

Generating descriptions:  71%|███████   | 167/235 [15:35<06:29,  5.72s/it]

Batch 166/235 sample → Tuerca M5 resistente para motores 4T de gasolina. Fijación segura y duradera, ideal para repuestos VARIOS MOTORES....

Generating descriptions:  71%|███████▏  | 168/235 [15:41<06:36,  5.92s/it]

Batch 167/235 sample → Cuchilla derecha TF545D para zanjeador Husqvarna. Accesorio de alto rendimiento que ofrece cortes precisos y durabilidad para surcos limpios....

Generating descriptions:  72%|███████▏  | 169/235 [15:44<05:30,  5.01s/it]

Batch 170/235 sample → Cuchilla derecha para motocultor Castoro. Filo afilado y resistente para cortes precisos en tus labores....

Generating descriptions:  72%|███████▏  | 170/235 [15:45<03:56,  3.64s/it]

Batch 169/235 sample → Rotatorio para picar TKC450, accesorio potente y duradero de Mitsubishi; consigue un labrado uniforme y eficiente en cada pasada....

Generating descriptions:  73%|███████▎  | 171/235 [16:01<07:59,  7.49s/it]

Batch 171/235 sample → Adaptador facial 902493 para casco Milenium Libus: accesorio de seguridad industrial, fácil de ajustar....

Generating descriptions:  73%|███████▎  | 172/235 [16:04<06:28,  6.17s/it]

Batch 174/235 sample → Transmisión Goldony para motocultor: robusta, precisa y lista para uso intensivo, instalación rápida....

Generating descriptions:  74%|███████▎  | 173/235 [16:07<05:16,  5.11s/it]

Batch 172/235 sample → MANGUERA DE FUMIGACIÓN NEGRA CON ROJO, 8.5 mm, 380 bar y espesor de 3.5 mm. Flexible, resistente y lista para fumigación de alto rendimiento....

Generating descriptions:  74%|███████▍  | 174/235 [16:09<04:22,  4.31s/it]

Batch 175/235 sample → Toberas de inyector GOLDONY 3LD: precisión y durabilidad para motocultores, optimizando la combustión y el rendimiento....

Generating descriptions:  74%|███████▍  | 175/235 [16:16<05:01,  5.03s/it]

Batch 173/235 sample → ACOPLE RAPIDO DE ALUMINIO F3, ligero y resistente; ideal para conectar sistemas de riego con bombas VARIOS BOMBAS....

Generating descriptions:  75%|███████▍  | 176/235 [16:21<04:51,  4.94s/it]

Batch 176/235 sample → Filtro de aire para fumigadora espolvoreadora Husqvarna 362 M18/362D28. Repuesto original....

Generating descriptions:  75%|███████▌  | 177/235 [16:27<05:15,  5.44s/it]

Batch 177/235 sample → Piñón loco ensamblado para transmisión CRT81 (532-14-45-62). Repuesto Husqvarna de alta durabilidad para una transmisión suave y fiable en tu motocolt...

Generating descriptions:  76%|███████▌  | 179/235 [16:33<03:30,  3.76s/it]

Batch 178/235 sample → Piñón de 27 dientes para CRT81 — repuesto original HUSQVARNA. Rendimiento confiable y duradero en transmisiones de motocultor....


Batch 180/235 sample → Cable de embrague resistente para motocultor Mitsubishi TKC450....

Generating descriptions:  77%|███████▋  | 180/235 [16:40<04:31,  4.93s/it]

Batch 181/235 sample → Palanca reguladora de velocidad TKC 650/750 — precisión y control suave para motocultor Mitsubishi. Conjunto robusto para cambios fiables....

Generating descriptions:  77%|███████▋  | 181/235 [16:44<04:07,  4.58s/it]

Batch 179/235 sample → Banda de transmisión para motocultor Husqvarna CRT51 y TR430. Numero de referencia 532-13-28-01. Duradera y fiable....

Generating descriptions:  77%|███████▋  | 182/235 [16:52<04:55,  5.57s/it]

Batch 183/235 sample → Cable de embrague principal Asiatech para motocultor Mitsubishi: resistente, con ajuste preciso y arranque suave....

Generating descriptions:  78%|███████▊  | 183/235 [16:58<04:53,  5.65s/it]

Batch 182/235 sample → Perno M5x40 hexagonal para motocultores. Acero resistente, ajuste seguro y fácil montaje....

Generating descriptions:  78%|███████▊  | 184/235 [16:59<03:38,  4.28s/it]

Batch 184/235 sample → Válvula de admisión para TKC450 - Mitsubishi. Repuesto confiable para un rendimiento óptimo del motor....

Generating descriptions:  79%|███████▊  | 185/235 [17:00<02:55,  3.51s/it]

Batch 186/235 sample → Cuchilla especial Asiatech Izquierda para motocultor Mitsubishi: precisión duradera para cortes limpios y eficientes....

Generating descriptions:  79%|███████▉  | 186/235 [17:10<04:16,  5.24s/it]

Batch 185/235 sample → JUEGO DE RINES TF545DE (186F) para motocultor Husqvarna. Construcción duradera y ajuste preciso para un rendimiento estable en el campo....

Generating descriptions:  80%|███████▉  | 187/235 [17:10<03:01,  3.78s/it]

Batch 187/235 sample → Repuesto principal estriado para la caja Asadón de GOLDONY. Construcción robusta, ajuste preciso y larga vida útil para motocultores....

Generating descriptions:  80%|████████  | 188/235 [17:22<04:51,  6.19s/it]

Batch 188/235 sample → Tapa de combustible GOLDONY para motocultor. Repuesto de alta durabilidad con ajuste perfecto, evita fugas y polvo, instalación rápida....

Generating descriptions:  80%|████████  | 189/235 [17:22<03:25,  4.47s/it]

Batch 189/235 sample → Cable de aceleración DTL-9000 para motoazada. Precisión y durabilidad para una aceleración suave, instalación rápida....

Generating descriptions:  81%|████████  | 190/235 [17:32<04:35,  6.13s/it]

Batch 191/235 sample → Amortiguador de soporte Pascualy de alto rendimiento. Repuesto resistente que absorbe impactos y mantiene estable el motor para un motocultor más suav...

Generating descriptions:  81%|████████▏ | 191/235 [17:33<03:18,  4.52s/it]

Batch 190/235 sample → Repuesto Mitsubishi para TKC450: Placa de ajuste, precisión y durabilidad para calibrar tu motocultor....

Generating descriptions:  82%|████████▏ | 192/235 [17:38<03:18,  4.61s/it]

Batch 192/235 sample → Cadena de transmisión de paso 40, 1/2 pulg (95E) para motocultor Husqvarna. Resistente y duradera para un rendimiento fiable en el campo....

Generating descriptions:  82%|████████▏ | 193/235 [17:39<02:29,  3.55s/it]

Batch 193/235 sample → Depurador de aire para TKC450 ALT (Mitsubishi). Repuesto original que mantiene el motor limpio y eficiente....

Generating descriptions:  83%|████████▎ | 194/235 [17:48<03:36,  5.28s/it]

Batch 194/235 sample → Tapa del timón Goldony 3LD510. Repuesto de alta durabilidad con ajuste perfecto y acabado brillante para tu motocultor....

Generating descriptions:  83%|████████▎ | 195/235 [17:49<02:34,  3.87s/it]

Batch 196/235 sample → CIGUEÑAL TKC450 – Motocultor Mitsubishi: pieza de alto rendimiento que aporta durabilidad y arranques fiables para tus labores en el campo....

Generating descriptions:  83%|████████▎ | 196/235 [17:51<02:11,  3.37s/it]

Batch 195/235 sample → Rodamiento JAF 5204 de BRIGS STRATON. Repuesto de alto rendimiento para motocultor: precisión y fiabilidad....

Generating descriptions:  84%|████████▍ | 197/235 [18:07<04:26,  7.01s/it]

Batch 198/235 sample → Embrague BT330 BESTONE/PASCUALY, repuesto de alta durabilidad para motocultor. Aporta acoplamiento suave y instalación rápida, compatible con varias m...

Generating descriptions:  84%|████████▍ | 198/235 [18:14<04:19,  7.02s/it]

Batch 197/235 sample → Perno de ajuste base rueda de cola TKC450 - Repuesto Mitsubishi para motocultor TKC450. Precisión y durabilidad para un ajuste seguro....

Generating descriptions:  85%|████████▍ | 199/235 [18:15<03:10,  5.28s/it]

Batch 200/235 sample → Adaptador rápido tipo D de 2 pulgadas con rosca interna, ideal para conexiones rápidas en sistemas de riego....

Generating descriptions:  85%|████████▌ | 200/235 [18:18<02:38,  4.53s/it]

Batch 199/235 sample → Manguera de succión anillada italiana verde, 5 bar, 3 pulgadas. Ali-Flex: resistente y flexible para bombeo y riego....

Generating descriptions:  86%|████████▌ | 201/235 [18:25<02:59,  5.28s/it]

Batch 201/235 sample → Acero de transmisión de 3 1/2 pulg con polea integrada; resistente y confiable para transmisiones en maquinaria agrícola y tornos....

Generating descriptions:  86%|████████▌ | 202/235 [18:33<03:28,  6.31s/it]

Batch 202/235 sample → Eje 19 mm inox exagonal para tornos. Robusto, preciso y resistente al desgaste....

Generating descriptions:  86%|████████▋ | 203/235 [18:43<03:57,  7.42s/it]

Batch 204/235 sample → Eje de transmisión en acero, 1 pulgada, hexagonal; alta resistencia y precisión para tornos industriales....

Generating descriptions:  87%|████████▋ | 204/235 [18:51<03:54,  7.56s/it]

Batch 207/235 sample → Transferencia automática 63A: conmutación rápida y confiable entre fuentes de alimentación. Ideal para maquinaria agrícola que exige continuidad y seg...

Generating descriptions:  87%|████████▋ | 205/235 [18:52<02:45,  5.50s/it]

Batch 205/235 sample → Tractor de giro cero HUSQVARNA GIRO ZERO MZ54: 24 HP, motor Kawasaki y 54 pulgadas de ancho de corte. Gran maniobrabilidad para jardines y huertos....

Generating descriptions:  88%|████████▊ | 206/235 [18:52<01:54,  3.94s/it]

Batch 203/235 sample → Eje excagonal de 3/4 pulgada para tuercas mango filtro. Construcción robusta y precisión para un ajuste seguro en tornos....

Generating descriptions:  88%|████████▊ | 207/235 [18:53<01:24,  3.01s/it]

Batch 206/235 sample → Rodamiento 6905 de BRIGS STRATON: alta durabilidad y precisión para motores eléctricos, ideal para maquinaria agrícola....

Generating descriptions:  89%|████████▊ | 208/235 [19:10<03:11,  7.10s/it]

Batch 209/235 sample → Banda de corte de repuesto para Husqvarna YTH2754. Rendimiento preciso y duradero, con instalación rápida para un césped perfecto....

Generating descriptions:  89%|████████▉ | 209/235 [19:17<03:04,  7.10s/it]

Batch 211/235 sample → Banda del tren de corte 15HP TS138 para tractores cortacésped. Husqvarna, rendimiento fiable y duradero....

Generating descriptions:  89%|████████▉ | 210/235 [19:19<02:21,  5.68s/it]

Batch 210/235 sample → Banda de corte de repuesto para tractor LT151/Murray 22HP. Ofrece durabilidad y un corte uniforme para un jardín impecable....


Batch 208/235 sample → Bomba de agua a presión CM-PRES de 2 pulgadas, 7 HP de MARUYAMA. Rendimiento fiable para sistemas de riego, con construcción robusta y puesta en march...

Generating descriptions:  90%|█████████ | 212/235 [19:30<02:06,  5.50s/it]

Batch 212/235 sample → Buje posterior +1 GOLDONY 3LD para motocultor. Duradero y preciso, mejora la estabilidad y el rendimiento en las labores agrícolas....

Generating descriptions:  91%|█████████ | 213/235 [19:40<02:24,  6.57s/it]

Batch 213/235 sample → Árbol de levas para motor diésel TEMCO 10HP (186F): precisión y durabilidad para motores 4T....

Generating descriptions:  91%|█████████ | 214/235 [19:46<02:14,  6.42s/it]

Batch 215/235 sample → Manilar tubular para STIHL FS450: repuesto duradero para guadañas con arranque cómodo y fiable....

Generating descriptions:  91%|█████████▏| 215/235 [19:47<01:40,  5.03s/it]

Batch 214/235 sample → Cuchilla izquierda para motocultor grande, FAB. Corta con precisión y durabilidad en labores pesadas. Compatible con VARIOS MOTORES....

Generating descriptions:  92%|█████████▏| 216/235 [19:53<01:42,  5.42s/it]

Batch 216/235 sample → Aceite 2T Husqvarna, 0,5 L. Lubrica y protege el motor de tu guadaña para un rendimiento duradero....

Generating descriptions:  93%|█████████▎| 218/235 [19:57<01:00,  3.58s/it]

Batch 218/235 sample → Conector de tubos multiusos Ducati DBC3301M-S 32.6CC: accesorio robusto para guadañas, con instalación rápida y compatibilidad entre motores para un r...


Batch 217/235 sample → Cabezales de hilo T45x M12 para guadañas Husqvarna. Rosca M12, carga rápida de hilo y mayor durabilidad para cortes limpios y productividad....

Generating descriptions:  93%|█████████▎| 219/235 [20:07<01:25,  5.33s/it]

Batch 220/235 sample → Sinfín MS360 antiguo para motosierras STIHL. Repuesto duradero y fiable para un rendimiento estable....

Generating descriptions:  94%|█████████▎| 220/235 [20:09<01:07,  4.48s/it]

Batch 219/235 sample → TANQUE MEZCLADOR DE GASOLINA 1LT – Accesorio para guadañas. Mezcla el combustible de forma rápida y segura (1 L)....

Generating descriptions:  94%|█████████▍| 221/235 [20:21<01:33,  6.65s/it]

Batch 223/235 sample → Carburador MS-455 para motosierra Husqvarna. Repuesto de alto rendimiento que mejora la mezcla aire/combustible y el rendimiento del motor; instalació...

Generating descriptions:  94%|█████████▍| 222/235 [20:22<01:02,  4.79s/it]

Batch 221/235 sample → Espada EFCO de 20 pulgadas, 325. Repuesto para motosierras de varias marcas. Corta con precisión y durabilidad para trabajos exigentes....

Generating descriptions:  95%|█████████▍| 223/235 [20:23<00:43,  3.62s/it]

Batch 222/235 sample → Escape de motosierra 365XP de Husqvarna. Repuesto original que garantiza rendimiento fiable y ajuste perfecto....

Generating descriptions:  95%|█████████▌| 224/235 [20:32<00:58,  5.32s/it]

Batch 224/235 sample → JUEGON PIÑON CADENA TIPO ANILLO 3/8 MS-310 - REPUESTO MOTOSIERRA STIHL: juego de piñón y cadena tipo anillo 3/8 MS-310, para mayor durabilidad y corte...

Generating descriptions:  96%|█████████▌| 225/235 [20:41<01:05,  6.52s/it]

Batch 225/235 sample → FILTRO DE AIRE BRIGS STRATON para cortacesret carrito; repuesto confiable que protege el motor y mejora la potencia....

Generating descriptions:  96%|█████████▌| 226/235 [20:45<00:50,  5.57s/it]

Batch 226/235 sample → Tubo de llanta posterior para Kubota B2320 (9-5-16 A). Repuesto resistente y confiable para las llantas traseras. Marca: VARIOS BOMBAS....

Generating descriptions:  97%|█████████▋| 228/235 [20:58<00:38,  5.53s/it]

Batch 228/235 sample → Árbol de levas para tractor Pouland Pro PP155642, repuesto de VARIOS MOTORES para un rendimiento suave y fiable....


Batch 227/235 sample → BANDA DE TREN DE CORTE para tractor Troy-Bilt de 42 pulgadas. Repuesto duradero para cortes limpios y precisos. Compatibilidad con motores de varios f...

Generating descriptions:  97%|█████████▋| 229/235 [21:00<00:26,  4.39s/it]

Batch 229/235 sample → Arranque completo LB155S para tractores Husqvarna: arranque rápido y fiabilidad duradera....

Generating descriptions:  98%|█████████▊| 230/235 [21:06<00:24,  4.87s/it]

Batch 230/235 sample → Cable de tracción para cortacésped Husqvarna, resistente y fácil de instalar; un repuesto esencial para arranques suaves y cortes precisos....

Generating descriptions:  98%|█████████▊| 231/235 [21:11<00:20,  5.19s/it]

Batch 231/235 sample → Motor a gasolina 4 tiempos Asiatech GB181 de Mitsubishi. Rendimiento fiable para maquinaria agrícola y trabajo intenso....

Generating descriptions:  99%|█████████▊| 232/235 [21:20<00:18,  6.28s/it]

Batch 234/235 sample → Acople mariposa de 10 mm con rosca 1/2; bronce, conexión rápida para líneas de fumigación....

Generating descriptions:  99%|█████████▉| 233/235 [21:25<00:11,  5.68s/it]

⚠️ JSON parsing failed in batch 231: Expecting ',' delimiter: line 17 column 39 (char 1544)

Batch 232/235 sample → {
  "4620": "Motor diesel 178F con chaveta, 8 HP: rendimiento estable y arranque rápido para maquinaria agrícola.",
  "4621": "Biela STD 46 mm para mo...

Generating descriptions: 100%|█████████▉| 234/235 [21:29<00:05,  5.37s/it]

Batch 233/235 sample → TUBO FLEXIBLE TIPO ACORDEON NUBOLA SR450 (STIHL) – Accesorio de fumigación flexible y duradero para maniobras en campo....

Generating descriptions: 100%|██████████| 235/235 [21:30<00:00,  5.49s/it]

Batch 235/235 sample → Conexión rápida y segura para sistemas de fumigación. Compatible con accesorios VARIOS BOMBAS....

In [48]:
final_df

,product_id,product_code,product_name,category_name,brand_name,price_cash,new_product,discount,link,main_boost,low_value_flag,popularity,description,brand_logo
0,0,0,.,SIN CATEGORIA,S.M.,0.0000,False,0,NaN,NaN,NaN,NaN,S.M. presenta un producto versátil y confiable...,/images/brands/placeholder.png
1,3368,700M-024,GATO HIDRAULICO TIPO BOTELLA,SIN CATEGORIA,VARIOS MOTORES,111.1525,False,0,NaN,NaN,NaN,NaN,GATO HIDRÁULICO TIPO BOTELLA de VARIOS MOTORES...,/images/brands/placeholder.png
2,4167,700M-121,TIJERA T-55C COSECHA Y PODA,SIN CATEGORIA,VARIOS MOTORES,0.0000,False,0,NaN,0.0,0.0,0.000583,TIJERA T-55C COSECHA Y PODA: cortes limpios y ...,/images/brands/placeholder.png
3,1,101-0066SI,"DESBROZADOR FS-450/ CUCHILLA, VISERA COMPLETA,...",MOTOGUADANAS,STIHL,902.9126,False,0,NaN,NaN,NaN,NaN,"DESBROZADOR FS-450 de STIHL: cuchilla, visera ...",/images/brands/placeholder.png
4,803,305-0106SI,DESBROZADORA B50R RIGIDA MARUYAMA,MOTOGUADANAS,MARUYAMA,776.6990,False,0,[https://campomaq.blob.core.windows.net/campom...,0.0,0.0,0.009280,DESBROZADORA B50R RÍGIDA MARUYAMA: rendimiento...,/images/brands/placeholder.png
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4688,4691,700B-547,BANDA DAYCO 15410,ACCESORIOS FUMIGACION,VARIOS BOMBAS,9.0000,False,0,NaN,NaN,NaN,NaN,Banda Dayco 15410: correa de transmisión para ...,/images/brands/placeholder.png
4689,4714,700B-112,POLEA 12 X 2 RANURAS TORNEADO,ACCESORIOS FUMIGACION,VARIOS BOMBAS,38.0000,False,0,NaN,0.0,0.0,0.000741,"Polea 12 x 2, ranuras torneadas: transmisión s...",/images/brands/placeholder.png
4690,4715,700B-111,POLEA 11 X 2 RANURAS TORNEADA,ACCESORIOS FUMIGACION,VARIOS BOMBAS,33.7500,False,0,NaN,0.0,0.0,0.000150,"Polea 11 x 2, ranuras torneada: transmisión es...",/images/brands/placeholder.png
4691,4756,308-0014SI,ACORDEON MD8026,ACCESORIOS FUMIGACION,MARUYAMA,16.4000,False,0,NaN,0.0,0.0,0.000101,Acordeón MD8026 (MARUYAMA): tramo flexible tip...,/images/brands/placeholder.png
4692,4764,700B-280,FLAUTA SALIDAS BOMBA DE FUMIGAR,ACCESORIOS FUMIGACION,VARIOS BOMBAS,0.0000,False,0,NaN,1.0,0.0,0.200908,Flauta de salidas para bomba de fumigación: di...,/images/brands/placeholder.png

# EMBEDDINGS

In [49]:
from concurrent.futures import ThreadPoolExecutor, as_completed
import math

def process_embedding_batch(i, texts, num_batches):
    response = client.embeddings.create(
        model="text-embedding-3-large",   # or "text-embedding-3-large" for higher accuracy
        input=texts,
        dimensions=256
    )
    embeddings = [item.embedding for item in response.data]

    # 👀 Print one example vector length per batch
    print(f"Batch {i+1}/{num_batches} → got {len(embeddings)} embeddings, dim={len(embeddings[0])}")

    return embeddings

def generate_embeddings_multithread(df, batch_size=50, max_workers=5):
    """
    Generate embeddings for product_name + category_name + brand_name
    using multithreaded batching.
    """
    # texts = [
    #     f"{row['product_name']} | {row['category_name']} | {row['brand_name']}"
    #     for _, row in df.iterrows()
    # ]

    texts = [
        f"{row['product_name']} | {row['brand_name']}"
        for _, row in df.iterrows()
    ]


    embeddings = [None] * len(texts)
    num_batches = math.ceil(len(texts) / batch_size)

    with ThreadPoolExecutor(max_workers=max_workers) as executor:
        futures = []
        for i in range(num_batches):
            batch_texts = texts[i*batch_size:(i+1)*batch_size]
            futures.append(executor.submit(process_embedding_batch, i, batch_texts, num_batches))

        batch_start = 0
        for future in tqdm(as_completed(futures), total=len(futures), desc="Generating embeddings"):
            batch_embeddings = future.result()
            # Insert results back into correct positions
            embeddings[batch_start:batch_start+len(batch_embeddings)] = batch_embeddings
            batch_start += len(batch_embeddings)

    return embeddings

# Run and add embeddings column
final_df["embedding"] = generate_embeddings_multithread(final_df, batch_size=30, max_workers=5)

Generating embeddings:   1%|▏         | 2/157 [00:01<02:03,  1.26it/s]

Batch 3/157 → got 30 embeddings, dim=256
Batch 2/157 → got 30 embeddings, dim=256
Batch 1/157 → got 30 embeddings, dim=256
Batch 4/157 → got 30 embeddings, dim=256

Generating embeddings:   3%|▎         | 5/157 [00:02<00:57,  2.66it/s]

Batch 9/157 → got 30 embeddings, dim=256

Generating embeddings:   4%|▍         | 7/157 [00:03<01:08,  2.19it/s]

Batch 7/157 → got 30 embeddings, dim=256
Batch 10/157 → got 30 embeddings, dim=256

Generating embeddings:   6%|▌         | 9/157 [00:04<00:52,  2.80it/s]

Batch 6/157 → got 30 embeddings, dim=256
Batch 11/157 → got 30 embeddings, dim=256
Batch 8/157 → got 30 embeddings, dim=256

Generating embeddings:   8%|▊         | 13/157 [00:04<00:32,  4.50it/s]

Batch 13/157 → got 30 embeddings, dim=256
Batch 14/157 → got 30 embeddings, dim=256
Batch 5/157 → got 30 embeddings, dim=256

Generating embeddings:   9%|▉         | 14/157 [00:05<00:44,  3.21it/s]

Batch 12/157 → got 30 embeddings, dim=256
Batch 16/157 → got 30 embeddings, dim=256

Generating embeddings:  11%|█▏        | 18/157 [00:06<00:28,  4.79it/s]

Batch 18/157 → got 30 embeddings, dim=256
Batch 15/157 → got 30 embeddings, dim=256
Batch 17/157 → got 30 embeddings, dim=256

Generating embeddings:  13%|█▎        | 20/157 [00:06<00:24,  5.51it/s]

Batch 20/157 → got 30 embeddings, dim=256
Batch 19/157 → got 30 embeddings, dim=256

Generating embeddings:  14%|█▍        | 22/157 [00:07<00:28,  4.76it/s]

Batch 23/157 → got 30 embeddings, dim=256
Batch 24/157 → got 30 embeddings, dim=256
Batch 21/157 → got 30 embeddings, dim=256

Generating embeddings:  15%|█▌        | 24/157 [00:07<00:24,  5.39it/s]

Batch 22/157 → got 30 embeddings, dim=256
Batch 25/157 → got 30 embeddings, dim=256

Generating embeddings:  17%|█▋        | 26/157 [00:07<00:21,  6.14it/s]

Batch 27/157 → got 30 embeddings, dim=256

Generating embeddings:  18%|█▊        | 29/157 [00:08<00:19,  6.70it/s]

Batch 26/157 → got 30 embeddings, dim=256
Batch 28/157 → got 30 embeddings, dim=256
Batch 30/157 → got 30 embeddings, dim=256

Generating embeddings:  19%|█▉        | 30/157 [00:08<00:32,  3.95it/s]

Batch 32/157 → got 30 embeddings, dim=256

Generating embeddings:  21%|██        | 33/157 [00:09<00:23,  5.26it/s]

Batch 33/157 → got 30 embeddings, dim=256
Batch 29/157 → got 30 embeddings, dim=256
Batch 34/157 → got 30 embeddings, dim=256
Batch 31/157 → got 30 embeddings, dim=256

Generating embeddings:  23%|██▎       | 36/157 [00:09<00:21,  5.59it/s]

Batch 35/157 → got 30 embeddings, dim=256
Batch 36/157 → got 30 embeddings, dim=256

Generating embeddings:  24%|██▎       | 37/157 [00:09<00:19,  6.15it/s]

Batch 38/157 → got 30 embeddings, dim=256
Batch 37/157 → got 30 embeddings, dim=256
Batch 39/157 → got 30 embeddings, dim=256

Generating embeddings:  25%|██▌       | 40/157 [00:10<00:17,  6.88it/s]

Batch 40/157 → got 30 embeddings, dim=256

Generating embeddings:  26%|██▌       | 41/157 [00:10<00:19,  6.08it/s]

Batch 41/157 → got 30 embeddings, dim=256
Batch 44/157 → got 30 embeddings, dim=256

Generating embeddings:  27%|██▋       | 43/157 [00:10<00:18,  6.05it/s]

Batch 43/157 → got 30 embeddings, dim=256
Batch 42/157 → got 30 embeddings, dim=256

Generating embeddings:  30%|██▉       | 47/157 [00:11<00:13,  8.06it/s]

Batch 47/157 → got 30 embeddings, dim=256
Batch 45/157 → got 30 embeddings, dim=256
Batch 46/157 → got 30 embeddings, dim=256

Generating embeddings:  31%|███       | 49/157 [00:11<00:17,  6.18it/s]

Batch 49/157 → got 30 embeddings, dim=256
Batch 51/157 → got 30 embeddings, dim=256
Batch 50/157 → got 30 embeddings, dim=256
Batch 52/157 → got 30 embeddings, dim=256

Generating embeddings:  35%|███▌      | 55/157 [00:12<00:12,  8.16it/s]

Batch 48/157 → got 30 embeddings, dim=256
Batch 56/157 → got 30 embeddings, dim=256
Batch 53/157 → got 30 embeddings, dim=256
Batch 54/157 → got 30 embeddings, dim=256
Batch 55/157 → got 30 embeddings, dim=256

Generating embeddings:  36%|███▋      | 57/157 [00:12<00:11,  8.62it/s]

Batch 57/157 → got 30 embeddings, dim=256
Batch 58/157 → got 30 embeddings, dim=256

Generating embeddings:  38%|███▊      | 59/157 [00:12<00:13,  7.23it/s]

Batch 59/157 → got 30 embeddings, dim=256
Batch 60/157 → got 30 embeddings, dim=256

Generating embeddings:  39%|███▉      | 62/157 [00:13<00:12,  7.32it/s]

Batch 62/157 → got 30 embeddings, dim=256
Batch 61/157 → got 30 embeddings, dim=256
Batch 63/157 → got 30 embeddings, dim=256

Generating embeddings:  41%|████▏     | 65/157 [00:13<00:12,  7.42it/s]

Batch 64/157 → got 30 embeddings, dim=256
Batch 66/157 → got 30 embeddings, dim=256

Generating embeddings:  43%|████▎     | 67/157 [00:14<00:14,  6.02it/s]

Batch 65/157 → got 30 embeddings, dim=256
Batch 69/157 → got 30 embeddings, dim=256
Batch 68/157 → got 30 embeddings, dim=256

Generating embeddings:  44%|████▍     | 69/157 [00:14<00:12,  6.93it/s]

Batch 70/157 → got 30 embeddings, dim=256
Batch 67/157 → got 30 embeddings, dim=256

Generating embeddings:  45%|████▌     | 71/157 [00:14<00:11,  7.29it/s]

Batch 71/157 → got 30 embeddings, dim=256

Generating embeddings:  46%|████▌     | 72/157 [00:14<00:14,  6.01it/s]

Batch 74/157 → got 30 embeddings, dim=256
Batch 72/157 → got 30 embeddings, dim=256

Generating embeddings:  47%|████▋     | 74/157 [00:15<00:15,  5.33it/s]

Batch 75/157 → got 30 embeddings, dim=256
Batch 76/157 → got 30 embeddings, dim=256
Batch 73/157 → got 30 embeddings, dim=256

Generating embeddings:  50%|████▉     | 78/157 [00:15<00:11,  7.00it/s]

Batch 77/157 → got 30 embeddings, dim=256
Batch 78/157 → got 30 embeddings, dim=256

Generating embeddings:  50%|█████     | 79/157 [00:16<00:12,  6.30it/s]

Batch 79/157 → got 30 embeddings, dim=256
Batch 81/157 → got 30 embeddings, dim=256
Batch 80/157 → got 30 embeddings, dim=256

Generating embeddings:  52%|█████▏    | 82/157 [00:16<00:10,  6.97it/s]

Batch 82/157 → got 30 embeddings, dim=256

Generating embeddings:  55%|█████▍    | 86/157 [00:16<00:07,  9.08it/s]

Batch 84/157 → got 30 embeddings, dim=256
Batch 86/157 → got 30 embeddings, dim=256
Batch 85/157 → got 30 embeddings, dim=256
Batch 83/157 → got 30 embeddings, dim=256

Generating embeddings:  57%|█████▋    | 90/157 [00:17<00:07,  9.05it/s]

Batch 88/157 → got 30 embeddings, dim=256
Batch 87/157 → got 30 embeddings, dim=256
Batch 90/157 → got 30 embeddings, dim=256
Batch 89/157 → got 30 embeddings, dim=256

Generating embeddings:  59%|█████▊    | 92/157 [00:17<00:08,  7.79it/s]

Batch 91/157 → got 30 embeddings, dim=256
Batch 92/157 → got 30 embeddings, dim=256

Generating embeddings:  60%|█████▉    | 94/157 [00:17<00:08,  7.73it/s]

Batch 93/157 → got 30 embeddings, dim=256
Batch 95/157 → got 30 embeddings, dim=256
Batch 94/157 → got 30 embeddings, dim=256

Generating embeddings:  62%|██████▏   | 98/157 [00:18<00:06,  9.37it/s]

Batch 96/157 → got 30 embeddings, dim=256
Batch 97/157 → got 30 embeddings, dim=256
Batch 98/157 → got 30 embeddings, dim=256

Generating embeddings:  63%|██████▎   | 99/157 [00:18<00:07,  7.77it/s]

Batch 100/157 → got 30 embeddings, dim=256

Generating embeddings:  64%|██████▍   | 101/157 [00:18<00:08,  6.44it/s]

Batch 99/157 → got 30 embeddings, dim=256
Batch 103/157 → got 30 embeddings, dim=256

Generating embeddings:  66%|██████▌   | 103/157 [00:18<00:06,  8.50it/s]

Batch 101/157 → got 30 embeddings, dim=256
Batch 102/157 → got 30 embeddings, dim=256
Batch 104/157 → got 30 embeddings, dim=256

Generating embeddings:  67%|██████▋   | 105/157 [00:19<00:07,  6.64it/s]

Batch 105/157 → got 30 embeddings, dim=256
Batch 106/157 → got 30 embeddings, dim=256

Generating embeddings:  70%|███████   | 110/157 [00:19<00:04, 10.12it/s]

Batch 107/157 → got 30 embeddings, dim=256
Batch 108/157 → got 30 embeddings, dim=256
Batch 109/157 → got 30 embeddings, dim=256
Batch 110/157 → got 30 embeddings, dim=256

Generating embeddings:  73%|███████▎  | 114/157 [00:20<00:04,  8.82it/s]

Batch 115/157 → got 30 embeddings, dim=256
Batch 111/157 → got 30 embeddings, dim=256
Batch 113/157 → got 30 embeddings, dim=256
Batch 112/157 → got 30 embeddings, dim=256
Batch 114/157 → got 30 embeddings, dim=256

Generating embeddings:  75%|███████▍  | 117/157 [00:20<00:05,  7.32it/s]

Batch 116/157 → got 30 embeddings, dim=256
Batch 117/157 → got 30 embeddings, dim=256
Batch 118/157 → got 30 embeddings, dim=256

Generating embeddings:  76%|███████▌  | 119/157 [00:20<00:04,  8.88it/s]

Batch 119/157 → got 30 embeddings, dim=256
Batch 120/157 → got 30 embeddings, dim=256

Generating embeddings:  77%|███████▋  | 121/157 [00:21<00:04,  8.44it/s]

Batch 121/157 → got 30 embeddings, dim=256

Generating embeddings:  80%|████████  | 126/157 [00:21<00:02, 12.36it/s]

Batch 123/157 → got 30 embeddings, dim=256
Batch 122/157 → got 30 embeddings, dim=256
Batch 125/157 → got 30 embeddings, dim=256
Batch 124/157 → got 30 embeddings, dim=256
Batch 126/157 → got 30 embeddings, dim=256

Generating embeddings:  83%|████████▎ | 130/157 [00:22<00:02,  9.04it/s]

Batch 127/157 → got 30 embeddings, dim=256
Batch 131/157 → got 30 embeddings, dim=256
Batch 128/157 → got 30 embeddings, dim=256
Batch 129/157 → got 30 embeddings, dim=256

Generating embeddings:  84%|████████▍ | 132/157 [00:22<00:03,  7.58it/s]

Batch 130/157 → got 30 embeddings, dim=256
Batch 133/157 → got 30 embeddings, dim=256
Batch 132/157 → got 30 embeddings, dim=256

Generating embeddings:  85%|████████▌ | 134/157 [00:22<00:02,  7.93it/s]

Batch 135/157 → got 30 embeddings, dim=256
Batch 134/157 → got 30 embeddings, dim=256

Generating embeddings:  88%|████████▊ | 138/157 [00:23<00:02,  8.78it/s]

Batch 136/157 → got 30 embeddings, dim=256
Batch 137/157 → got 30 embeddings, dim=256
Batch 139/157 → got 30 embeddings, dim=256
Batch 138/157 → got 30 embeddings, dim=256

Generating embeddings:  89%|████████▉ | 140/157 [00:23<00:01,  8.94it/s]

Batch 141/157 → got 30 embeddings, dim=256
Batch 140/157 → got 30 embeddings, dim=256

Generating embeddings:  92%|█████████▏| 144/157 [00:23<00:01,  8.41it/s]

Batch 142/157 → got 30 embeddings, dim=256
Batch 143/157 → got 30 embeddings, dim=256
Batch 146/157 → got 30 embeddings, dim=256

Generating embeddings:  93%|█████████▎| 146/157 [00:24<00:01,  9.80it/s]

Batch 144/157 → got 30 embeddings, dim=256
Batch 145/157 → got 30 embeddings, dim=256

Generating embeddings:  94%|█████████▍| 148/157 [00:24<00:01,  7.38it/s]

Batch 147/157 → got 30 embeddings, dim=256
Batch 148/157 → got 30 embeddings, dim=256
Batch 150/157 → got 30 embeddings, dim=256

Generating embeddings:  96%|█████████▌| 150/157 [00:24<00:00,  9.03it/s]

Batch 149/157 → got 30 embeddings, dim=256

Generating embeddings:  97%|█████████▋| 152/157 [00:24<00:00,  7.77it/s]

Batch 153/157 → got 30 embeddings, dim=256
Batch 151/157 → got 30 embeddings, dim=256
Batch 152/157 → got 30 embeddings, dim=256

Generating embeddings:  99%|█████████▉| 156/157 [00:25<00:00,  9.69it/s]

Batch 155/157 → got 30 embeddings, dim=256
Batch 154/157 → got 30 embeddings, dim=256
Batch 156/157 → got 30 embeddings, dim=256

Generating embeddings: 100%|██████████| 157/157 [00:25<00:00,  6.18it/s]

Batch 157/157 → got 13 embeddings, dim=256

In [51]:
final_df['updated_at'] = pd.Timestamp.now()
final_df['created_at'] = pd.Timestamp.now()

In [53]:
# New field to indicate that the product is shown in the catalog
top_100_codes = (
    df_top_sales_prods.sort_values("popularity", ascending=False)
    .head(100)["product_code"]
    .tolist()
)

# Assign True for top 100, False for others
final_df["show_in_app"] = final_df["product_code"].isin(top_100_codes)

In [60]:
final_df['is_spare_part'] = True

### Prepare the final dataframe for MongoDB insertion

In [61]:
# final_df.info()
import numpy as np

def prepare_catalog_df(df: pd.DataFrame) -> pd.DataFrame:
    # --- Handle nulls ---
    # Replace NaN with None (Mongo stores None as null)
    df = df.replace({np.nan: None})
    
    # Ensure link is always a list (empty list if null)
    if "link" in df.columns:
        df["link"] = df["link"].apply(lambda x: x if isinstance(x, list) else ([] if x is None else [x]))
    
    # Replace nulls in numeric fields with 0.0
    numeric_fill_zero = ["main_boost", "low_value_flag", "popularity"]
    for col in numeric_fill_zero:
        if col in df.columns:
            df[col] = df[col].fillna(0.0)
    
    # Ensure booleans are actual Python bool
    bool_fields = ["new_product", "show_in_app","is_spare_part"]
    for field in bool_fields:
        if field in df.columns:
            df[field] = df[field].astype(bool)
    
    # --- Sort by popularity ---
    if "popularity" in df.columns:
        df = df.sort_values(by="popularity", ascending=False).reset_index(drop=True)
    
    return df

final_mongo_df = prepare_catalog_df(final_df)

/var/folders/z_/f3rpfjgn6j1bwmghgxsm9nbm0000gn/T/ipykernel_77839/1503058880.py:17: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(0.0)

In [ ]:
final_mongo_df.head()

,product_id,product_code,product_name,category_name,brand_name,price_cash,new_product,discount,link,main_boost,low_value_flag,popularity,description,brand_logo,embedding,updated_at,created_at,show_in_app,is_spare_part
0,1155,408-0009SI,MOTOCULTOR TF545DE ARRANQUE ELECTRICO,MOTOCULTORES,HUSQVARNA,2300.0000,True,0,[https://campomaq.blob.core.windows.net/campom...,1.0,0.0,0.700122,Motocultor TF545DE con arranque eléctrico: pot...,/images/brands/placeholder.png,"[0.017649561166763306, 0.0108011644333601, -0....",2025-09-10 19:08:18.274767,2025-09-10 19:08:18.281328,True,True
1,3189,700-0001,MOTOCULTOR TKC-450,MOTOCULTORES,MITSUBISHI,5400.0000,False,0,[https://campomaq.blob.core.windows.net/campom...,1.0,0.0,0.457468,Motocultor TKC-450. Rendimiento robusto y mane...,/images/brands/placeholder.png,"[0.01142564695328474, -0.003175643738359213, -...",2025-09-10 19:08:18.274767,2025-09-10 19:08:18.281328,True,True
2,4482,700M-578,MOTOCULTOR TOPO Y LEVANTACAMAS,MOTOCULTORES,VARIOS MOTORES,0.0000,False,0,[],1.0,0.0,0.240174,Motocultor topo y levantacamás. Herramienta mu...,/images/brands/placeholder.png,"[-0.04533183574676514, 0.020423460751771927, -...",2025-09-10 19:08:18.274767,2025-09-10 19:08:18.281328,True,True
3,4285,700M-490SI,CUCHILLA CURVA IZQUIERDA APORCAR MOTOCULTOR TF...,ACCESORIOS MOTOCULTORES,HUSQVARNA,7.7500,False,0,[],1.0,1.0,0.232496,"Cuchilla curva izquierda para aporcar, TF545DE...",/images/brands/placeholder.png,"[0.0073365718126297, 0.07551898807287216, -0.0...",2025-09-10 19:08:18.274767,2025-09-10 19:08:18.281328,True,True
4,882,311-0012SI,CILINDRO BOMBA 653/655,REPUESTOS FUMIGACION,MARUYAMA,115.0000,False,0,[https://campomaq.blob.core.windows.net/campom...,1.0,0.0,0.231187,Cilindro bomba 653/655 MARUYAMA. Rendimiento e...,/images/brands/placeholder.png,"[-0.014922961592674255, -0.007976065389811993,...",2025-09-10 19:08:18.274767,2025-09-10 19:08:18.281328,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4688,2604,700M-332,RETENEDOR GRANDE DESBROZADOR CHINO 15*35*5,REPUESTOS MOTOGUADANAS,VARIOS MOTORES,2.4294,False,0,[https://campomaq.blob.core.windows.net/campom...,0.0,0.0,0.000000,Retenedor grande para desbrozador chino 15x35x...,/images/brands/placeholder.png,"[-0.06828673183917999, 0.0005414062179625034, ...",2025-09-10 19:08:18.274767,2025-09-10 19:08:18.281328,False,True
4689,2787,700M-976A,BULON DE TIJERA PODAR FELCO,ACCESORIOS FUMIGACION,VARIOS MOTORES,5.7412,False,0,[],0.0,0.0,0.000000,Bulón de tijera podar Felco. Repuesto duradero...,/images/brands/placeholder.png,"[-0.015556911006569862, -0.01859593577682972, ...",2025-09-10 19:08:18.274767,2025-09-10 19:08:18.281328,False,True
4690,3104,3104,700B-058SI,ACCESORIOS FUMIGACION,VARIOS BOMBAS,0.0000,False,0,[],0.0,0.0,0.000000,700B-058SI - Accesorio de fumigación compacto ...,/images/brands/placeholder.png,"[-0.06223153695464134, -0.058573149144649506, ...",2025-09-10 19:08:18.274767,2025-09-10 19:08:18.281328,False,True
4691,3105,700B-058SI,MANGO FILTRO METALICO M/H 1/4,ACCESORIOS FUMIGACION,VARIOS BOMBAS,20.0000,False,0,[],0.0,0.0,0.000000,MANGO FILTRO METALICO M/H 1/4. Filtro metálico...,/images/brands/placeholder.png,"[-0.017637891694903374, -0.02634907141327858, ...",2025-09-10 19:08:18.274767,2025-09-10 19:08:18.281328,False,True
4692,0,0,.,SIN CATEGORIA,S.M.,0.0000,False,0,[],0.0,0.0,0.000000,S.M. presenta un producto versátil y confiable...,/images/brands/placeholder.png,"[0.08922729641199112, 0.0347549133002758, 0.02...",2025-09-10 19:08:18.274767,2025-09-10 19:08:18.281328,False,True

In [65]:
mongo_uri = os.environ['MONGO_URI']
client = MongoClient(mongo_uri, server_api=ServerApi('1'))

if cm_env == 'prod':
    collection = client["campomaq"]["cm_catalog"]
else:
    collection = client["campomaq_test"]["cm_catalog"]

if not final_mongo_df.empty:
    # Convert DataFrame to JSON
    records = final_mongo_df.to_dict(orient="records")
    collection.insert_many(records)
    print(f"✅ Inserted {len(records)} records into MongoDB")

else:
    print("No new data to insert.")

✅ Inserted 4693 records into MongoDB

# New field to indicate that the product is shown in the catalogm

In [6]:
# Select the database and collection
cm_env = os.environ.get('CM_ENV', 'dev')
if cm_env == 'prod':
    collection = client["campomaq"]["cm_catalog"]
else:
    collection = client["campomaq_test"]["cm_catalog"]

# New field to indicate that the product is shown in the catalog
top_100_codes = (
    df_top_sales_prods.sort_values("popularity", ascending=False)
    .head(100)["product_code"]
    .tolist()
)

# Assign True for top 100, False for others
df_top_sales_prods["show_in_app"] = df_top_sales_prods["product_code"].isin(top_100_codes)

from pymongo import UpdateOne

# Build bulk operations
operations = [
    UpdateOne(
        {"product_code": row["product_code"]},
        {"$set": {"show_in_app": bool(row["show_in_app"])}}
    )
    for _, row in df_top_sales_prods.iterrows()
]
# Execute in bulk
if operations:
    result = collection.bulk_write(operations, ordered=False)
    print(f"Matched: {result.matched_count}, Modified: {result.modified_count}")

Matched: 2591, Modified: 2591