In [1]:
import os
from dotenv import load_dotenv, find_dotenv
from pymongo import MongoClient
import pandas as pd
from pymongo.server_api import ServerApi

# Load environment variables
load_dotenv(find_dotenv())

# Connect to MongoDB
mongo_uri = os.environ['MONGO_URI']
client = MongoClient(mongo_uri, server_api=ServerApi('1'))

In [2]:
# TOP SALES PRODUCTS
cm_env = os.environ.get('CM_ENV', 'dev')
if cm_env == 'prod':
    collection = client["campomaq"]["cm_top_sales_products"]
else:
    collection = client["campomaq_test"]["cm_top_sales_products"]

# Read all documents from the collection
cursor = collection.find({})
df_top_sales_prods = pd.DataFrame(list(cursor))

In [3]:
df_top_sales_prods

,_id,product_code,product_name,brand_name,category_name,quantity,sale_without_iva,total_cost,profit,main_boost,low_value_flag,quantity_norm,profit_norm,popularity
0,68a20061cec08c7d52913f54,408-0009SI,MOTOCULTOR TF545DE ARRANQUE ELECTRICO,HUSQVARNA ...,MOTOCULTORES ...,29,90930.000000,49013.093333,41916.906667,1,0,0.000306,1.000000,0.700122
1,68a20061cec08c7d52913f55,700-0001,MOTOCULTOR TKC-450,MITSUBISHI ...,MOTOCULTORES ...,7,37600.000000,18828.281338,18771.718662,1,0,0.000066,0.447832,0.423942
2,68a20061cec08c7d52913f56,700M-578,MOTOCULTOR TOPO Y LEVANTACAMAS,VARIOS MOTORES ...,MOTOCULTORES ...,3,13650.000000,10282.800000,3367.200000,1,0,0.000022,0.080330,0.240174
3,68a20061cec08c7d52913f57,700M-490SI,CUCHILLA CURVA IZQUIERDA APORCAR MOTOCULTOR TF...,HUSQVARNA ...,ACCESORIOS MOTOCULTORES ...,447,3538.345000,1016.925000,2521.420000,1,1,0.001950,0.060153,0.230856
4,68a20061cec08c7d52913f58,700M-491SI,CUCHILLA CURVA DERECHA APORCAR MOTOCULTOR TF545DE,HUSQVARNA ...,ACCESORIOS MOTOCULTORES ...,443,3506.675000,1007.825000,2498.850000,1,1,0.001932,0.059614,0.230580
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2586,68a20061cec08c7d5291496e,700B-331,LANZA CIRCULAR 5 SALIDAS ALUMINIO,VARIOS BOMBAS ...,ACCESORIOS FUMIGACION ...,1,0.000000,4.276800,0.010000,0,0,0.000000,0.000000,0.000000
2587,68a20061cec08c7d5291496f,700M-311,"LLAVE 3/4"" MEDIA VUELTA",VARIOS BOMBAS ...,ACCESORIOS DE RIEGO ...,1,6.521739,10.120000,0.010000,0,0,0.000000,0.000000,0.000000
2588,68a20061cec08c7d52914970,700B-345,BANDA A-26,VARIOS BOMBAS ...,ACCESORIOS FUMIGACION ...,1,4.086957,4.130400,0.010000,0,0,0.000000,0.000000,0.000000
2589,68a20061cec08c7d52914971,440-0051,GUIA DE TEMPLADOR 365,HUSQVARNA ...,REPUESTOS MOTOSIERRAS ...,1,2.913043,4.953333,0.010000,0,0,0.000000,0.000000,0.000000
2590,68a20061cec08c7d52914972,406-0002,CARBURADOR MS-125,HUSQVARNA ...,REPUESTOS MOTOSIERRAS ...,1,29.660870,41.400000,0.010000,0,0,0.000000,0.000000,0.000000

In [10]:
df_top_sales_prods = df_top_sales_prods[["product_code", "main_boost", "low_value_flag", "popularity"]]

In [3]:
# PRODUCTS
cm_env = os.environ.get('CM_ENV', 'dev')
if cm_env == 'prod':
    collection = client["campomaq"]["cm_productos"]
else:
    collection = client["campomaq_test"]["cm_productos"]

# Read all documents from the collection
cursor = collection.find({})
df_products = pd.DataFrame(list(cursor))

In [16]:
df_products = df_products[["product_id","product_code", "product_name", "category_name", "brand_name","price_cash"]]

In [17]:
df_products

,product_id,product_code,product_name,category_name,brand_name,price_cash
0,0,0,. ...,SIN CATEGORIA ...,S.M. ...,0.0000
1,3368,700M-024,GATO HIDRAULICO TIPO BOTELLA ...,SIN CATEGORIA ...,VARIOS MOTORES ...,111.1525
2,4167,700M-121,TIJERA T-55C COSECHA Y PODA ...,SIN CATEGORIA ...,VARIOS MOTORES ...,0.0000
3,1,101-0066SI,"DESBROZADOR FS-450/ CUCHILLA, VISERA COMPLETA,...",MOTOGUADANAS ...,STIHL ...,902.9126
4,803,305-0106SI,DESBROZADORA B50R RIGIDA MARUYAMA ...,MOTOGUADANAS ...,MARUYAMA ...,776.6990
...,...,...,...,...,...,...
4783,4567,S000077,ARMADO EQUIPO DE TRANSFERENCIA AUTOMATICO ...,SERVICIOS ...,SERVICIOS ...,0.0000
4784,4568,S000078,FIJACION TUBERIA CONDUIT (TRABAJO EN ALTURA) ...,SERVICIOS ...,SERVICIOS ...,0.0000
4785,4569,S000079,CABLEADO INTER ESTRUCTURAL DE 50M LONGITUD ...,SERVICIOS ...,SERVICIOS ...,0.0000
4786,4570,S000080,"INSTALACION EN SITIO TRANSFERENCIA, PRUEBAS DE...",SERVICIOS ...,SERVICIOS ...,0.0000
4787,4571,700M-665,TUBERIA CONDUIT ...,SERVICIOS ...,SERVICIOS ...,0.0000

In [27]:
# Select the database and collection
cm_env = os.environ.get('CM_ENV', 'dev')
if cm_env == 'prod':
    collection = client["campomaq"]["cm_images"]
else:
    collection = client["campomaq_test"]["cm_images"]

# Read all documents from the collection
cursor = collection.find({})
df_product_images = pd.DataFrame(list(cursor))

In [29]:
df_product_images = df_product_images[['product_id','link','index']]
df_product_images

      product_id                                               link index
0             10  [https://campomaq.blob.core.windows.net/campom...   [0]
1             14  [https://campomaq.blob.core.windows.net/campom...   [0]
2             19  [https://campomaq.blob.core.windows.net/campom...   [0]
3             20  [https://campomaq.blob.core.windows.net/campom...   [0]
4             21  [https://campomaq.blob.core.windows.net/campom...   [0]
...          ...                                                ...   ...
2372        4189  [https://campomaq.blob.core.windows.net/campom...   [0]
2373        4192  [https://campomaq.blob.core.windows.net/campom...   [0]
2374        4193  [https://campomaq.blob.core.windows.net/campom...   [0]
2375        4232  [https://campomaq.blob.core.windows.net/campom...   [0]
2376        4233  [https://campomaq.blob.core.windows.net/campom...   [0]

[2377 rows x 3 columns]

In [30]:
# 2. Join products with images on product_id
prod_img_df = df_products.merge(df_product_images, on="product_id", how="left")

# 3. Join with popularity_df on product_code df_top_sales_prods
final_df = df_top_sales_prods.merge(prod_img_df, on="product_code", how="left")

In [32]:
final_df

,product_code,main_boost,low_value_flag,popularity,product_id,product_name,category_name,brand_name,price_cash,link,index
0,408-0009SI,1,0,0.700122,1155,MOTOCULTOR TF545DE ARRANQUE ELECTRICO ...,MOTOCULTORES ...,HUSQVARNA ...,2300.0000,[https://campomaq.blob.core.windows.net/campom...,"[0, 2, 3]"
1,700-0001,1,0,0.423942,3189,MOTOCULTOR TKC-450 ...,MOTOCULTORES ...,MITSUBISHI ...,5400.0000,[https://campomaq.blob.core.windows.net/campom...,[0]
2,700M-578,1,0,0.240174,4482,MOTOCULTOR TOPO Y LEVANTACAMAS ...,MOTOCULTORES ...,VARIOS MOTORES ...,0.0000,NaN,NaN
3,700M-490SI,1,1,0.230856,4285,CUCHILLA CURVA IZQUIERDA APORCAR MOTOCULTOR TF...,ACCESORIOS MOTOCULTORES ...,HUSQVARNA ...,7.7500,NaN,NaN
4,700M-491SI,1,1,0.230580,4286,CUCHILLA CURVA DERECHA APORCAR MOTOCULTOR TF54...,ACCESORIOS MOTOCULTORES ...,HUSQVARNA ...,7.5000,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
2586,700B-331,0,0,0.000000,4227,LANZA CIRCULAR 5 SALIDAS ALUMINIO ...,ACCESORIOS FUMIGACION ...,VARIOS BOMBAS ...,0.0000,NaN,NaN
2587,700M-311,0,0,0.000000,2487,"LLAVE 3/4"" MEDIA VUELTA ...",ACCESORIOS DE RIEGO ...,VARIOS BOMBAS ...,10.7202,[https://campomaq.blob.core.windows.net/campom...,[0]
2588,700B-345,0,0,0.000000,2314,BANDA A-26 ...,ACCESORIOS FUMIGACION ...,VARIOS BOMBAS ...,4.8345,NaN,NaN
2589,440-0051,0,0,0.000000,1718,GUIA DE TEMPLADOR 365 ...,REPUESTOS MOTOSIERRAS ...,HUSQVARNA ...,7.3000,[https://campomaq.blob.core.windows.net/campom...,[0]
2590,406-0002,0,0,0.000000,4312,CARBURADOR MS-125 ...,REPUESTOS MOTOSIERRAS ...,HUSQVARNA ...,59.0000,NaN,NaN

In [33]:
import openai
from openai import OpenAI
from dotenv import load_dotenv, find_dotenv
from tqdm import tqdm
import math
import json
from concurrent.futures import ThreadPoolExecutor, as_completed


# Load environment variables
load_dotenv(find_dotenv())
tqdm.pandas()

openai.api_key = os.environ['OPENAI_API_KEY']
# Initialize client
client = OpenAI()


# Function to process one batch
def process_batch(i, batch, num_batches):
    prompt = "Write concise and appealing product descriptions for an agricultural machinery e-commerce site.\n\n"
    for idx, row in batch.iterrows():
        prompt += f"Product {idx}:\n"
        prompt += f"Name: {row['product_name']}\n"
        prompt += f"Category: {row['category_name']}\n"
        prompt += f"Brand: {row['brand_name']}\n\n"
    prompt += "Return the results as JSON with keys being the product index and values being the description."

    response = client.chat.completions.create(
        model="gpt-5-nano",  # you can switch model here
        messages=[{"role": "user", "content": prompt}],
        # temperature=0.7
    )

    try:
        batch_desc = json.loads(response.choices[0].message.content)
    except Exception as e:
        print(f"⚠️ JSON parsing failed in batch {i}: {e}")
        batch_desc = {str(idx): response.choices[0].message.content for idx in batch.index}

    # 👀 Print one sample from this batch
    sample_idx = next(iter(batch.index))
    print(f"\nBatch {i+1}/{num_batches} sample → {batch_desc.get(str(sample_idx), '')[:150]}...\n")

    return batch_desc

# Main function
def generate_descriptions_multithread(df, batch_size=20, max_workers=5):
    descriptions = {}
    num_batches = math.ceil(len(df) / batch_size)

    with ThreadPoolExecutor(max_workers=max_workers) as executor:
        futures = []
        for i in range(num_batches):
            batch = df.iloc[i*batch_size:(i+1)*batch_size]
            futures.append(executor.submit(process_batch, i, batch, num_batches))

        for future in tqdm(as_completed(futures), total=len(futures), desc="Generating descriptions"):
            batch_desc = future.result()
            for k, v in batch_desc.items():
                descriptions[int(k)] = v

    return [descriptions[idx] for idx in df.index]

# Run with multithreading
final_df["description"] = generate_descriptions_multithread(final_df, batch_size=20, max_workers=5)

Generating descriptions:   1%|          | 1/130 [00:15<33:45, 15.70s/it]

Batch 2/130 sample → Bomba de agua 3x3 pulgadas, alta presión, arranque eléctrico y motor diésel; rendimiento confiable para riego de alto caudal. VARIOS BOMBAS....

Generating descriptions:   2%|▏         | 2/130 [00:16<14:11,  6.65s/it]

Batch 1/130 sample → Motocultor Husqvarna TF545DE con arranque eléctrico: potencia y comodidad para labrar huertos y pequeñas parcelas....

Generating descriptions:   2%|▏         | 3/130 [00:17<09:17,  4.39s/it]

Batch 4/130 sample → Bomba de agua con motor KHOLER 6.5 HP para riego: caudal estable, rendimiento fiable y construcción robusta....

Generating descriptions:   3%|▎         | 4/130 [00:19<07:07,  3.39s/it]

Batch 3/130 sample → Neumático multifunción para motocultor Ducatti, ofrece excelente tracción y durabilidad en todo tipo de terrenos, repuesto confiable para desempeño co...

Generating descriptions:   4%|▍         | 5/130 [00:20<05:21,  2.57s/it]

Batch 5/130 sample → Bomba periférica nueva PKM60-MD (Pedrollo) 0,5 HP, 110V, 60 Hz. Conexión 1x1, ideal para riego....

Generating descriptions:   5%|▍         | 6/130 [00:31<11:26,  5.54s/it]

Batch 7/130 sample → ANILLO O BOMBA MS055/056/068/073D – Repuestos de fumigación MARUYAMA. Anillo de bomba compatible con MS055/MS056/MS068/MS073D para rendimiento y durab...

Generating descriptions:   5%|▌         | 7/130 [00:34<09:10,  4.48s/it]

Batch 6/130 sample → Bomba de aceite para motosierra STIHL MS382; repuesto de lubricación fiable....

Generating descriptions:   6%|▌         | 8/130 [00:37<08:27,  4.16s/it]

Batch 10/130 sample → Empaque de pistón MS-653/655 MS40V (632588) para sistemas de presión. Repuesto MARUYAMA para fumigación....

Generating descriptions:   7%|▋         | 9/130 [00:39<07:09,  3.55s/it]

Batch 9/130 sample → Cuchilla general izquierda para motocultor TF545DE (Husqvarna); repuesto de alto rendimiento Ducatti....

Generating descriptions:   8%|▊         | 10/130 [00:40<05:28,  2.74s/it]

Batch 8/130 sample → Bomba de combustible (bombín) completa FS-560 para motoguadañas STIHL. Repuesto original, rendimiento fiable para arranque y suministro de combustible...

Generating descriptions:   8%|▊         | 11/130 [00:45<06:37,  3.34s/it]

Batch 11/130 sample → Aceite 15W40 en galón para motores 4T a gasolina, ofrece lubricación confiable y protección para el rendimiento diario de la maquinaria....

Generating descriptions:   9%|▉         | 12/130 [00:54<09:49,  4.99s/it]

Batch 12/130 sample → Uniones de 8.5 mm con rosca 1/4; accesorio para sistemas de fumigación, compatible con VARIOS BOMBAS....

Generating descriptions:  11%|█         | 14/130 [00:57<05:49,  3.02s/it]

Batch 13/130 sample → Pasadores de llantas TF545DE, repuesto original Husqvarna para motocultores; montaje seguro y duradero....


Batch 14/130 sample → ALBUZ LILA ATR, accesorio de fumigación de VARIOS BOMBAS: diseño para aplicación precisa y fiable....

Generating descriptions:  12%|█▏        | 15/130 [00:57<04:24,  2.30s/it]

Batch 15/130 sample → Manguera de unión 8 mm para sistemas de fumigación. Flexible y resistente, facilita conexiones seguras entre bombas y boquillas....

Generating descriptions:  12%|█▏        | 16/130 [01:07<08:46,  4.61s/it]

Batch 16/130 sample → Cadena TKC450/650 para motocultor Mitsubishi: cadena de gran resistencia para labranza y trabajos intensivos. Alta durabilidad, instalación sencilla y...

Generating descriptions:  13%|█▎        | 17/130 [01:15<10:17,  5.47s/it]

Batch 17/130 sample → Valvula VRP CPL 653/655 de MARUYAMA, repuesto de fumigacion; precision y fiabilidad para tu equipo....

Generating descriptions:  14%|█▍        | 18/130 [01:15<07:19,  3.92s/it]

Batch 19/130 sample → Cabezal de nailon 130 mm para guadañas, ligero y resistente. Proporciona cortes uniformes y reemplazo rápido....

Generating descriptions:  15%|█▍        | 19/130 [01:19<07:34,  4.09s/it]

Batch 20/130 sample → Bujía 4 tiempos con mecha corta B7HS, repuesto fiable para motores a gasolina....

Generating descriptions:  15%|█▌        | 20/130 [01:22<06:35,  3.60s/it]

Batch 18/130 sample → Espigo 1/4 hembra con rosca interna, accesorio de fumigación compatible con bombas VARIOS BOMBAS; construcción duradera para conexiones rápidas y segu...

Generating descriptions:  16%|█▌        | 21/130 [01:28<07:53,  4.34s/it]

Batch 21/130 sample → Arrancador de gasolina 11-13 HP para motores 4T. Arranque rápido y fiable; compatible con TEMCO....

Generating descriptions:  17%|█▋        | 22/130 [01:32<07:48,  4.34s/it]

Batch 23/130 sample → Cubierta de arranque CPL143RII 505-30-17-01 para motoguadañas Husqvarna. Repuesto original de alto rendimiento para un arranque fiable....

Generating descriptions:  18%|█▊        | 24/130 [01:43<07:35,  4.30s/it]

Batch 24/130 sample → Tornillo de ajuste para cubiertas TKC450, repuesto original Mitsubishi; garantiza ajuste preciso y duradero en motocultores....


Batch 22/130 sample → Manómetro AR-30/50 de repuesto para fumigación. Lectura clara y precisión fiable para controlar la presión en equipos ANNOVI REVERVERI....

Generating descriptions:  19%|█▉        | 25/130 [01:48<08:16,  4.73s/it]

Batch 26/130 sample → Rotatorio para motocultor TKC450 (Mitsubishi): accesorio robusto para picar y rotar labores en el campo....


Batch 25/130 sample → BRAZO DE TENSION TKC450 EQ – Repuesto original Mitsubishi para el sistema de correa TKC450 EQ; duradero y preciso para un rendimiento estable....

Generating descriptions:  21%|██        | 27/130 [01:56<07:16,  4.23s/it]

Batch 27/130 sample → Sello de aceite para selector de marchas ASIATECH, compatible con motocultor Mitsubishi. Sello duradero que garantiza cambios suaves y protege contra ...

Generating descriptions:  22%|██▏       | 28/130 [01:59<06:41,  3.94s/it]

Batch 28/130 sample → Aceite 2T 120cc para motoguadañas Husqvarna. Lubricante de alto rendimiento que protege el motor y mantiene la potencia....

Generating descriptions:  22%|██▏       | 29/130 [02:08<08:52,  5.28s/it]

Batch 31/130 sample → Extensión en acero inoxidable para lanza de fumigación; resistente y duradera, ideal para pulverización de precisión en campo....

Generating descriptions:  23%|██▎       | 30/130 [02:13<08:51,  5.32s/it]

Batch 29/130 sample → Eje de fresa con cuchillas para zanjador TF545DE/DTL900. Repuesto original Husqvarna para alto rendimiento y durabilidad....

Generating descriptions:  24%|██▍       | 31/130 [02:13<06:27,  3.92s/it]

Batch 32/130 sample → Visor de malla metálica para motoguadañas MARUYAMA. Repuesto duradero que protege ojos de impactos y chispas....

Generating descriptions:  25%|██▍       | 32/130 [02:17<06:02,  3.70s/it]

Batch 30/130 sample → Tapa de arranque CPL BC4320 282294SI para motoguadañas MARUYAMA. Repuesto original que protege el sistema de encendido y facilita un arranque confiabl...

Generating descriptions:  25%|██▌       | 33/130 [02:17<04:32,  2.81s/it]

Batch 33/130 sample → Válvula TS22 de POW: repuesto de fumigación que ofrece precisión y durabilidad para tus equipos....

Generating descriptions:  26%|██▌       | 34/130 [02:34<11:11,  7.00s/it]

Batch 34/130 sample → Biela AR-50 de ANNOVI REVERVERI para sistemas de fumigación; repuesto de alta resistencia para un rendimiento fiable....

Generating descriptions:  27%|██▋       | 35/130 [02:36<08:44,  5.52s/it]

Batch 38/130 sample → Desbrozador Goodyear GY27521S, 51.7 cc y 1.95 HP: desbrozadora a gasolina para maleza densa, con diseño ergonómico y rendimiento fiable....

Generating descriptions:  28%|██▊       | 36/130 [02:44<09:39,  6.17s/it]

Batch 36/130 sample → AHOYADORA DUCATI DEA5200 CON BROCA 8 (DEA17752). Amoladora angular de la gama MOTOGUADANAS de DUCATTI, con broca de 8 mm incluida para mantenimiento....

Generating descriptions:  28%|██▊       | 37/130 [02:46<07:46,  5.02s/it]

Batch 35/130 sample → Cable de embrague rotatorio ASIATECH para motocultor Mitsubishi. Repuesto de alta resistencia que garantiza cambios suaves y durabilidad....

Generating descriptions:  29%|██▉       | 38/130 [02:55<09:30,  6.20s/it]

Batch 37/130 sample → Polea de hierro fundido torneada, 2 1/2 in x 2 in. Construcción robusta para accesorios de fumigación; ideal para uso continuo en sistemas de tracción...

Generating descriptions:  30%|███       | 39/130 [02:56<06:50,  4.51s/it]

Batch 40/130 sample → Arrancador para motosierras de origen chino. Repuesto robusto y económico, fácil de montar para varios modelos y arranques rápidos en trabajos foresta...

Generating descriptions:  31%|███       | 40/130 [02:56<04:54,  3.27s/it]

Batch 39/130 sample → Terminales eléctricos para motores 4T a gasolina. Compatibles con varias marcas (VARIOS MOTORES); conexiones seguras y duraderas....

Generating descriptions:  32%|███▏      | 41/130 [03:09<09:11,  6.20s/it]

Batch 42/130 sample → Brazo completo de repuesto para motoguadaña MARUYAMA, compatible con BC420, BC500, BC4320 y BF43R. Construcción duradera y montaje rápido para un rend...

Generating descriptions:  32%|███▏      | 42/130 [03:15<08:46,  5.98s/it]

Batch 41/130 sample → Cable y funda de mando para la función de parada STOP de GOLDONY. Repuesto fiable para motocultores compatibles....

Generating descriptions:  33%|███▎      | 43/130 [03:20<08:12,  5.66s/it]

Batch 44/130 sample → Motosierra EFCO 55cc, 3.5 HP, barra de 20 pulgadas y cadena de 39 dientes. Potencia y durabilidad para trabajos forestales....

Generating descriptions:  34%|███▍      | 44/130 [03:21<06:15,  4.37s/it]

Batch 43/130 sample → KIT DE BOQUILLAS DE LANZA DE FUMIGACION (DISCOD5): conjunto de repuestos para pulverización con caudal preciso y cobertura homogénea....

Generating descriptions:  35%|███▍      | 45/130 [03:22<04:36,  3.26s/it]

Batch 45/130 sample → Piñón PTF 740 para motocultores; compatible con BESTONE/PASCUALY (repuesto VARIOS MOTORES)....

Generating descriptions:  35%|███▌      | 46/130 [03:38<10:13,  7.31s/it]

Batch 50/130 sample → Funda de cuchilla izquierda para TKC450 y TDR250; protege la cuchilla y facilita el mantenimiento en motocultores Mitsubishi....

Generating descriptions:  36%|███▌      | 47/130 [03:41<08:04,  5.84s/it]

Batch 49/130 sample → Mando de aceleración completo para motoguadañas (R/China-Shindaiwa); repuesto versátil para varios motores....

Generating descriptions:  37%|███▋      | 48/130 [03:45<07:05,  5.19s/it]

Batch 46/130 sample → BANDA DAYCO 17480: Correa de repuesto Dayco para sistemas de fumigación; alta durabilidad y compatibilidad con múltiples bombas....

Generating descriptions:  38%|███▊      | 49/130 [03:50<06:58,  5.16s/it]

Batch 48/130 sample → Filtro de aceite de repuesto para tractor, compatible con Troy-Bilt y fabricado por Oleomac; ofrece filtración eficiente y mayor durabilidad para un m...

Generating descriptions:  38%|███▊      | 50/130 [03:53<06:02,  4.54s/it]

Batch 47/130 sample → Cuchilla de repuesto de 20" para cortacésped Husqvarna, compatible con HU700, LB155S y LC151S (2013)....

Generating descriptions:  39%|███▉      | 51/130 [04:02<07:53,  5.99s/it]

Batch 51/130 sample → BANDA B42 – Banda de fumigación flexible para sellado y conexión en sistemas de pulverización; compatible con VARIOS BOMBAS....

Generating descriptions:  40%|████      | 52/130 [04:03<05:48,  4.47s/it]

Batch 52/130 sample → Llave de bola 1/2. Herramienta de mano resistente para mantenimiento de equipos agrícolas y accesorios de fumigación....

Generating descriptions:  41%|████      | 53/130 [04:07<05:40,  4.42s/it]

Batch 53/130 sample → Filtro de succión TS22-28 de TEMCO: accesorio de fumigación de alto rendimiento, sellado fiable y fácil instalación....

Generating descriptions:  42%|████▏     | 54/130 [04:16<07:20,  5.79s/it]

Batch 54/130 sample → Rueda económica para carretilla, 8 in x 2.5-4, ideal para trasiego y labores de fumigación....

Generating descriptions:  42%|████▏     | 55/130 [04:17<05:09,  4.12s/it]

⚠️ JSON parsing failed in batch 54: Expecting ',' delimiter: line 16 column 26 (char 1510)

Batch 55/130 sample → {
  "1080": "Clip de seguro para pistón compatible con MARUYAMA BF43R/4320/420/500. Repuesto confiable para un funcionamiento suave y seguro del motor...

Generating descriptions:  43%|████▎     | 56/130 [04:23<06:03,  4.92s/it]

Batch 57/130 sample → Banda B-44, accesorio de fumigación para bombas (VARIOS BOMBAS); duradera y confiable....


Batch 56/130 sample → Torno de uso industrial para mantenimiento de maquinaria agrícola; alta precisión y durabilidad para reparaciones en taller....

Generating descriptions:  45%|████▍     | 58/130 [04:37<07:03,  5.88s/it]

Batch 60/130 sample → Polea de mandril para tractor Pouland Pro 21–24 HP. Repuesto robusto y fácil de instalar para tareas de corte y mantenimiento del césped....

Generating descriptions:  45%|████▌     | 59/130 [04:42<06:32,  5.53s/it]

Batch 62/130 sample → Valvulas TS22 de POW para equipos de fumigación: rendimiento fiable y duradero....

Generating descriptions:  46%|████▌     | 60/130 [04:43<05:05,  4.36s/it]

Batch 58/130 sample → Valvula de admision TKC450 para motocultor Mitsubishi. Repuesto de calidad para rendimiento fiable y mayor durabilidad....

Generating descriptions:  47%|████▋     | 61/130 [04:47<04:59,  4.34s/it]

Batch 61/130 sample → Rodamiento NTN 7505 BG de BRIGS STRATON, repuesto para motores 4T (gasolina y diésel); alta precisión y durabilidad para un rendimiento fiable....

Generating descriptions:  48%|████▊     | 62/130 [04:51<04:54,  4.33s/it]

Batch 59/130 sample → Tubo de escape con silenciador para motores 4T de 10 HP (diésel/gasolina). Fabricado por TEMCO, reduce el ruido y mejora el rendimiento....

Generating descriptions:  48%|████▊     | 63/130 [04:59<05:54,  5.29s/it]

Batch 63/130 sample → Trinquete BG86 Sopladora, repuesto STIHL para fumigación, diseño duradero y rendimiento confiable....

Generating descriptions:  49%|████▉     | 64/130 [05:02<04:57,  4.50s/it]

Batch 64/130 sample → Carburador original STIHL 4137/28A para KM-85R; precisión y rendimiento fiables para motoguadañas....

Generating descriptions:  50%|█████     | 65/130 [05:07<05:12,  4.80s/it]

Batch 65/130 sample → Repuesto de escape para motoguadañas MARUYAMA BC420/BC420H: construcción robusta y rendimiento fiable....

Generating descriptions:  51%|█████     | 66/130 [05:16<06:14,  5.86s/it]

Batch 66/130 sample → Cilindro para motoguadaña (China). Repuesto versátil para motores de motoguadañas....

Generating descriptions:  52%|█████▏    | 67/130 [05:17<04:48,  4.57s/it]

Batch 69/130 sample → Tuerca M8.8 negra de paso normal; accesorio fiable para fijaciones en fumigación, compatible con múltiples motores....

Generating descriptions:  52%|█████▏    | 68/130 [05:25<05:48,  5.61s/it]

Batch 68/130 sample → Pistón motor TEMCO de 13HP para motores 4T (gasolina y diésel); alto rendimiento y durabilidad....

Generating descriptions:  53%|█████▎    | 69/130 [05:27<04:34,  4.49s/it]

Batch 67/130 sample → Perno M10x20 con cabeza redonda dorada para accesorios de fumigación. Duradero y fácil de instalar en equipos agrícolas....

Generating descriptions:  54%|█████▍    | 70/130 [05:30<04:05,  4.09s/it]

Batch 70/130 sample → Válvula de admisión y escape para GX390 (13 HP) - repuesto TEMCO para motores a gasolina 4T....

Generating descriptions:  55%|█████▍    | 71/130 [05:38<04:58,  5.05s/it]

Batch 72/130 sample → Accesorios de conducto para motores eléctricos; compatibles con VARIOS MOTORES; durables y fáciles de instalar para instalaciones seguras....

Generating descriptions:  55%|█████▌    | 72/130 [05:41<04:24,  4.55s/it]

Batch 71/130 sample → Kit de resortes de aceleración TKC450 para motocultor Mitsubishi. Repuesto original para mejorar la respuesta del acelerador y el rendimiento del moto...

Generating descriptions:  56%|█████▌    | 73/130 [05:50<05:38,  5.94s/it]

Batch 74/130 sample → Cable de embrague giratorio TKC 650/750 (2000133). Repuesto original Mitsubishi para motocultor; robusto y de instalación rápida....

Generating descriptions:  57%|█████▋    | 74/130 [05:52<04:29,  4.81s/it]

Batch 73/130 sample → JAULA DE AGUJAS 10x16x13 para MS-660/650/382 (CANASTILLA EMBRAGUE) – repuestos STIHL...

Generating descriptions:  58%|█████▊    | 75/130 [05:56<04:01,  4.40s/it]

Batch 75/130 sample → Perno 3/8 x 3 1/2 pulgadas, repuesto robusto para equipos de fumigación; compatible con múltiples motores....

Generating descriptions:  58%|█████▊    | 76/130 [05:56<02:52,  3.20s/it]

Batch 76/130 sample → Malla de mango filtro para sistemas de fumigación. Filtra impurezas y protege bombas y boquillas. Compatible con VARIOS BOMBAS....

Generating descriptions:  59%|█████▉    | 77/130 [06:07<04:46,  5.40s/it]

Batch 77/130 sample → Cable Bowden Nubola SR450 (STIHL) – Repuestos Fumigación: precisión y durabilidad para tus equipos de fumigación....

Generating descriptions:  61%|██████    | 79/130 [06:12<03:13,  3.79s/it]

Batch 79/130 sample → Mazo de cable MS-382 para motosierras STIHL: acabado resistente y ajuste preciso....


Batch 78/130 sample → Repuesto de tubo de llanta delantero GOLDONY para motocultor, compatible con llanta 5.00-12 y el modelo B2320....

Generating descriptions:  62%|██████▏   | 80/130 [06:17<03:20,  4.02s/it]

Batch 80/130 sample → Polea torneada de 4 1/2 pulgadas por 2 con ranuras; repuesto robusto para sistemas de fumigación y bombas compatibles....

Generating descriptions:  62%|██████▏   | 81/130 [06:20<03:01,  3.70s/it]

Batch 81/130 sample → Conector macho 1/4 con rosca externa para líneas de fumigación; compatible con bombas VARIOS BOMBAS....

Generating descriptions:  63%|██████▎   | 82/130 [06:28<04:10,  5.22s/it]

Batch 84/130 sample → FILTRO DE AIRE FS-160/280 (STIHL) para motoguadañas: protege el motor de polvo y mantiene un rendimiento óptimo....

Generating descriptions:  64%|██████▍   | 83/130 [06:29<03:05,  3.95s/it]

Batch 83/130 sample → Switch presostato para compresor de aire; repuesto esencial para motores 4T a gasolina y diesel (VARIOS MOTORES)....

Generating descriptions:  65%|██████▍   | 84/130 [06:30<02:21,  3.08s/it]

Batch 82/130 sample → Empaque de cabezote TEMCO para motores 4T a gasolina, 6.5 HP. Sellado duradero para un rendimiento estable....

Generating descriptions:  65%|██████▌   | 85/130 [06:38<03:23,  4.53s/it]

Batch 85/130 sample → Sello de aceite doble cara para MARUYAMA SB426/528/534, Y30524 y 546. Repuesto duradero para sistemas de fumigación....

Generating descriptions:  66%|██████▌   | 86/130 [06:42<03:02,  4.16s/it]

Batch 86/130 sample → Ducha de fumigación con 400 orificios para una pulverización uniforme; compatible con múltiples bombas para un rendimiento eficiente en campo....

Generating descriptions:  67%|██████▋   | 87/130 [06:52<04:23,  6.13s/it]

Batch 88/130 sample → Codo 90 3/8 – accesorio de fumigación (VARIOS BOMBAS)....

Generating descriptions:  68%|██████▊   | 88/130 [06:59<04:26,  6.36s/it]

Batch 89/130 sample → Filtro de aire interno para Kubota L4400. Alto rendimiento y durabilidad para repuestos de tractores compatibles....

Generating descriptions:  68%|██████▊   | 89/130 [07:01<03:30,  5.13s/it]

⚠️ JSON parsing failed in batch 86: Expecting ',' delimiter: line 8 column 28 (char 807)

Batch 87/130 sample → {
  "1720": "Repuesto de alto rendimiento: tubo de salida de aire STIHL para BG86, duradero y que mantiene un flujo de aire óptimo.",
  "1721": "Cabez...

Generating descriptions:  69%|██████▉   | 90/130 [07:06<03:17,  4.95s/it]

Batch 90/130 sample → Carburador HT131 para motoguadañas STIHL. Repuesto de alto rendimiento que garantiza arranque fácil y mezcla eficiente....

Generating descriptions:  70%|███████   | 91/130 [07:08<02:36,  4.01s/it]

Batch 91/130 sample → CARCASA IZQUIERDA TIJERA GOODYEAR GY2802PSS - Repuesto izquierdo para tijera Goodyear GY2802PSS, ajuste preciso y durabilidad....

Generating descriptions:  71%|███████   | 92/130 [07:20<04:05,  6.47s/it]

Batch 92/130 sample → Kit de tornillos cuchilla tijera Goodyear GY2802PSS. Conjunto de tornillos de repuesto para cuchilla tijera, duradero y de instalación fácil....

Generating descriptions:  72%|███████▏  | 93/130 [07:24<03:35,  5.83s/it]

Batch 94/130 sample → Biela de motor TEMCO para motores 4T de 11–13 HP (gasolina y diésel)....

Generating descriptions:  72%|███████▏  | 94/130 [07:30<03:25,  5.70s/it]

Batch 95/130 sample → BANDA DAYCO 15330 — Correa de repuesto para bombas de fumigación. Alta resistencia y durabilidad para uso continuo....

Generating descriptions:  73%|███████▎  | 95/130 [07:32<02:40,  4.60s/it]

Batch 93/130 sample → Perno de fijación 5/16 x 3 1/2 y 2 1/2 pulgadas; accesorio para fumigación....

Generating descriptions:  74%|███████▍  | 96/130 [07:34<02:09,  3.80s/it]

Batch 96/130 sample → Carburador original STIHL para MS660 y Jet Pro: rendimiento estable y fácil ajuste....

Generating descriptions:  75%|███████▍  | 97/130 [07:44<03:08,  5.70s/it]

Batch 97/130 sample → Manillar FS-280 para motoguadaña STIHL. Repuesto ergonómico y robusto que mejora el control y la comodidad durante la siega....

Generating descriptions:  75%|███████▌  | 98/130 [07:45<02:17,  4.30s/it]

Batch 98/130 sample → EMPAQUE TUBO DE ESCAPE 13HP de TEMCO, repuesto para motores 4T de gasolina y diesel, garantiza sellado fiable y rendimiento óptimo....

Generating descriptions:  76%|███████▌  | 99/130 [07:50<02:25,  4.68s/it]

Batch 99/130 sample → CABEZA NYLON 420 de MARUYAMA, accesorio de guadañas, duradera y de alto rendimiento para cortes limpios....

Generating descriptions:  77%|███████▋  | 100/130 [07:54<02:14,  4.47s/it]

Batch 100/130 sample → Caucho superior fuelle VRP 253-330 para equipos MARUYAMA. Sellado fiable y duradero para fumigación de alto rendimiento....

Generating descriptions:  78%|███████▊  | 101/130 [07:56<01:44,  3.61s/it]

Batch 101/130 sample → Cable de aceleración BC420 para motoguadañas MARUYAMA; repuesto original con respuesta suave y duradera....

Generating descriptions:  78%|███████▊  | 102/130 [08:06<02:31,  5.43s/it]

Batch 102/130 sample → Buje de cuchilla de repuesto para motoguadaña Maruyama, compatible con BCF-420/500/142R/4320; duradero y ofrece cortes precisos....


Batch 103/130 sample → Piñón del árbol de levas KM131R – repuesto de precisión para motoguadañas STIHL....

Generating descriptions:  80%|████████  | 104/130 [08:14<02:05,  4.82s/it]

Batch 104/130 sample → Pistón de alta durabilidad compatible con Husqvarna 142R/143R/BF43 (código 531-00-77-52). Repuesto esencial para restaurar rendimiento y confiabilidad...

Generating descriptions:  81%|████████  | 105/130 [08:18<01:53,  4.55s/it]

Batch 106/130 sample → Retén de repuesto 30x62x12 para sistemas de fumigacion; sellado fiable y duradero en motores variados....

Generating descriptions:  82%|████████▏ | 106/130 [08:21<01:41,  4.24s/it]

Batch 105/130 sample → Kit de carburador para guadaña (China). Repuesto para motores variados....

Generating descriptions:  82%|████████▏ | 107/130 [08:33<02:28,  6.46s/it]

Batch 107/130 sample → BASE SUCCIÓN DE ENTRADA TS-30 POW – Repuesto para sistemas de fumigación; base robusta, conexión segura y resistencia a químicos....

Generating descriptions:  83%|████████▎ | 108/130 [08:36<01:57,  5.32s/it]

Batch 109/130 sample → Gatillo acelerador compatible con Husqvarna 365/372/390/395, repuesto de alta durabilidad....

Generating descriptions:  84%|████████▍ | 109/130 [08:38<01:32,  4.39s/it]

Batch 108/130 sample → Guia de cadena de plastico para Husqvarna 268/288/365/372/395; repuesto de alta durabilidad y facil montaje....

Generating descriptions:  85%|████████▍ | 110/130 [08:43<01:29,  4.50s/it]

Batch 110/130 sample → Palanca de bloqueo de repuesto para motosierras MS381, STIHL: seguridad y bloqueo rápido de la cadena....

Generating descriptions:  85%|████████▌ | 111/130 [08:48<01:27,  4.62s/it]

Batch 111/130 sample → Kit de empaques para motosierra Husqvarna (modelos M61, 390, 395, 288, 660). Repuestos para sellado y durabilidad....

Generating descriptions:  86%|████████▌ | 112/130 [08:55<01:36,  5.38s/it]

Batch 112/130 sample → Filtro de aire de repuesto para cortacésped Goodyear GY51/53LM; protege el motor de polvo y desgaste....

Generating descriptions:  87%|████████▋ | 113/130 [08:58<01:21,  4.79s/it]

Batch 113/130 sample → Resorte de embrague para motores 4T a gasolina/diesel MARUYAMA - Robin...

Generating descriptions:  88%|████████▊ | 114/130 [09:08<01:39,  6.24s/it]

Batch 115/130 sample → Rodela 1/2 Plana, accesorio de fumigación para múltiples motores; resistencia y rendimiento confiables....

Generating descriptions:  88%|████████▊ | 115/130 [09:09<01:12,  4.81s/it]

Batch 114/130 sample → Válvula de descompresión MS-361 de STIHL: repuesto clave para arranques suaves y rendimiento fiable en motosierras....

Generating descriptions:  89%|████████▉ | 116/130 [09:13<01:05,  4.65s/it]

Batch 117/130 sample → Kit de reparación de arrancador (trinquete) para STIHL FS280: arranques fiables y reparación duradera....

Generating descriptions:  90%|█████████ | 117/130 [09:22<01:14,  5.72s/it]

Batch 116/130 sample → Cubierta de carcasa de bujía para STIHL FS-460/291. Repuesto original que garantiza encendido fiable y rendimiento estable....

Generating descriptions:  91%|█████████ | 118/130 [09:23<00:52,  4.38s/it]

Batch 118/130 sample → Tambor del cordón compatible con STIHL 025/361; repuesto duradero para motosierras....

Generating descriptions:  92%|█████████▏| 119/130 [09:33<01:06,  6.09s/it]

Batch 120/130 sample → Empaque Carter 362M18/362D28 para fumigación Husqvarna: sellado hermético y duradero para un rendimiento confiable....

Generating descriptions:  92%|█████████▏| 120/130 [09:36<00:50,  5.04s/it]

Batch 119/130 sample → Retenedor de sellos de alta durabilidad para MARUYAMA 253/330; repuesto de fumigacion....

Generating descriptions:  93%|█████████▎| 121/130 [09:42<00:50,  5.58s/it]

Batch 121/130 sample → Eje estriado de repuesto para motocultor CRT81 (Husqvarna). Precisión y durabilidad para trabajo rudo....

Generating descriptions:  94%|█████████▍| 122/130 [09:47<00:42,  5.36s/it]

Batch 123/130 sample → Carburador original STIHL MS660: repuesto de precisión para un rendimiento óptimo y arranques fiables en motosierras....

Generating descriptions:  95%|█████████▍| 123/130 [09:52<00:35,  5.07s/it]

Batch 122/130 sample → Repuesto para motosierra Husqvarna 125. Duradero y fiable para mantenimiento y reparaciones....

Generating descriptions:  95%|█████████▌| 124/130 [09:52<00:22,  3.77s/it]

Batch 124/130 sample → Cuchilla derecha CRT51 para motocultor Husqvarna; repuesto de alto rendimiento y durabilidad....

Generating descriptions:  96%|█████████▌| 125/130 [10:06<00:33,  6.68s/it]

Batch 126/130 sample → Retenedor 32x48x8 mm — accesorio de precisión para sistemas de fumigación; compatible con una amplia gama de motores....

Generating descriptions:  97%|█████████▋| 126/130 [10:08<00:21,  5.43s/it]

Batch 125/130 sample → Palanca de aceleración STIHL para guadañas FS 170/180. Control preciso del régimen de giro y montaje fácil para mayor comodidad....

Generating descriptions:  98%|█████████▊| 127/130 [10:09<00:12,  4.00s/it]

Batch 129/130 sample → Cable tren de corte Pouland Pro 16.5HP: repuesto robusto para tractores; rendimiento fiable y durabilidad en trabajos de siega y cultivo....

Generating descriptions:  98%|█████████▊| 128/130 [10:16<00:09,  4.80s/it]

Batch 127/130 sample → RETENEDOR ENGRANAJE 236R 143RII – Repuesto HUSQVARNA para motoguadañas; duradero y compatible con 236R/143RII....

Generating descriptions:  99%|█████████▉| 129/130 [10:18<00:04,  4.06s/it]

Batch 130/130 sample → Polea 051/076/MS-381, repuesto STIHL para motosierras; durabilidad y rendimiento confiable....

Generating descriptions: 100%|██████████| 130/130 [10:23<00:00,  4.79s/it]

Batch 128/130 sample → Bobina de repuesto CIFARELLI para equipos de fumigación de la marca SOLO....

In [34]:
final_df

,product_code,main_boost,low_value_flag,popularity,product_id,product_name,category_name,brand_name,price_cash,link,index,description
0,408-0009SI,1,0,0.700122,1155,MOTOCULTOR TF545DE ARRANQUE ELECTRICO ...,MOTOCULTORES ...,HUSQVARNA ...,2300.0000,[https://campomaq.blob.core.windows.net/campom...,"[0, 2, 3]",Motocultor Husqvarna TF545DE con arranque eléc...
1,700-0001,1,0,0.423942,3189,MOTOCULTOR TKC-450 ...,MOTOCULTORES ...,MITSUBISHI ...,5400.0000,[https://campomaq.blob.core.windows.net/campom...,[0],Motocultor Mitsubishi TKC-450: rendimiento y m...
2,700M-578,1,0,0.240174,4482,MOTOCULTOR TOPO Y LEVANTACAMAS ...,MOTOCULTORES ...,VARIOS MOTORES ...,0.0000,NaN,NaN,Motocultor Topo y Levantacamas: versátil para ...
3,700M-490SI,1,1,0.230856,4285,CUCHILLA CURVA IZQUIERDA APORCAR MOTOCULTOR TF...,ACCESORIOS MOTOCULTORES ...,HUSQVARNA ...,7.7500,NaN,NaN,Cuchilla curva izquierda para Motocultor TF545...
4,700M-491SI,1,1,0.230580,4286,CUCHILLA CURVA DERECHA APORCAR MOTOCULTOR TF54...,ACCESORIOS MOTOCULTORES ...,HUSQVARNA ...,7.5000,NaN,NaN,Cuchilla curva derecha para Motocultor TF545DE...
...,...,...,...,...,...,...,...,...,...,...,...,...
2586,700B-331,0,0,0.000000,4227,LANZA CIRCULAR 5 SALIDAS ALUMINIO ...,ACCESORIOS FUMIGACION ...,VARIOS BOMBAS ...,0.0000,NaN,NaN,Lanza circular de aluminio 5 salidas – accesor...
2587,700M-311,0,0,0.000000,2487,"LLAVE 3/4"" MEDIA VUELTA ...",ACCESORIOS DE RIEGO ...,VARIOS BOMBAS ...,10.7202,[https://campomaq.blob.core.windows.net/campom...,[0],Llave de 3/4 pulgadas media vuelta – accesorio...
2588,700B-345,0,0,0.000000,2314,BANDA A-26 ...,ACCESORIOS FUMIGACION ...,VARIOS BOMBAS ...,4.8345,NaN,NaN,Banda A-26 – accesorio de fumigación para apli...
2589,440-0051,0,0,0.000000,1718,GUIA DE TEMPLADOR 365 ...,REPUESTOS MOTOSIERRAS ...,HUSQVARNA ...,7.3000,[https://campomaq.blob.core.windows.net/campom...,[0],Guía de templador 365 para motosierras Husqvar...
2590,406-0002,0,0,0.000000,4312,CARBURADOR MS-125 ...,REPUESTOS MOTOSIERRAS ...,HUSQVARNA ...,59.0000,NaN,NaN,Carburador MS-125 para Husqvarna – rendimiento...

In [ ]:
from concurrent.futures import ThreadPoolExecutor, as_completed
import math

def process_embedding_batch(i, texts, num_batches):
    response = client.embeddings.create(
        model="text-embedding-3-large",   # or "text-embedding-3-large" for higher accuracy
        input=texts,
        dimensions=256
    )
    embeddings = [item.embedding for item in response.data]

    # 👀 Print one example vector length per batch
    print(f"Batch {i+1}/{num_batches} → got {len(embeddings)} embeddings, dim={len(embeddings[0])}")

    return embeddings

def generate_embeddings_multithread(df, batch_size=50, max_workers=5):
    """
    Generate embeddings for product_name + category_name + brand_name
    using multithreaded batching.
    """
    texts = [
        f"{row['product_name']} | {row['category_name']} | {row['brand_name']}"
        for _, row in df.iterrows()
    ]

    embeddings = [None] * len(texts)
    num_batches = math.ceil(len(texts) / batch_size)

    with ThreadPoolExecutor(max_workers=max_workers) as executor:
        futures = []
        for i in range(num_batches):
            batch_texts = texts[i*batch_size:(i+1)*batch_size]
            futures.append(executor.submit(process_embedding_batch, i, batch_texts, num_batches))

        batch_start = 0
        for future in tqdm(as_completed(futures), total=len(futures), desc="Generating embeddings"):
            batch_embeddings = future.result()
            # Insert results back into correct positions
            embeddings[batch_start:batch_start+len(batch_embeddings)] = batch_embeddings
            batch_start += len(batch_embeddings)

    return embeddings

# Run and add embeddings column
final_df["embedding"] = generate_embeddings_multithread(final_df, batch_size=30, max_workers=5)

Generating embeddings:   1%|          | 1/87 [00:02<03:13,  2.25s/it]

Batch 4/87 → got 30 embeddings, dim=256

Generating embeddings:   2%|▏         | 2/87 [00:02<01:37,  1.15s/it]

Batch 1/87 → got 30 embeddings, dim=256
Batch 3/87 → got 30 embeddings, dim=256
Batch 5/87 → got 30 embeddings, dim=256

Generating embeddings:   7%|▋         | 6/87 [00:03<00:35,  2.28it/s]

Batch 2/87 → got 30 embeddings, dim=256
Batch 6/87 → got 30 embeddings, dim=256
Batch 7/87 → got 30 embeddings, dim=256
Batch 8/87 → got 30 embeddings, dim=256

Generating embeddings:  11%|█▏        | 10/87 [00:04<00:21,  3.62it/s]

Batch 9/87 → got 30 embeddings, dim=256
Batch 13/87 → got 30 embeddings, dim=256
Batch 12/87 → got 30 embeddings, dim=256

Generating embeddings:  15%|█▍        | 13/87 [00:04<00:17,  4.12it/s]

Batch 10/87 → got 30 embeddings, dim=256
Batch 15/87 → got 30 embeddings, dim=256

Generating embeddings:  16%|█▌        | 14/87 [00:05<00:19,  3.84it/s]

Batch 11/87 → got 30 embeddings, dim=256
Batch 14/87 → got 30 embeddings, dim=256

Generating embeddings:  22%|██▏       | 19/87 [00:05<00:09,  7.21it/s]

Batch 16/87 → got 30 embeddings, dim=256
Batch 18/87 → got 30 embeddings, dim=256
Batch 20/87 → got 30 embeddings, dim=256
Batch 17/87 → got 30 embeddings, dim=256

Generating embeddings:  24%|██▍       | 21/87 [00:06<00:09,  6.87it/s]

Batch 19/87 → got 30 embeddings, dim=256
Batch 21/87 → got 30 embeddings, dim=256

Generating embeddings:  28%|██▊       | 24/87 [00:06<00:08,  7.47it/s]

Batch 23/87 → got 30 embeddings, dim=256
Batch 22/87 → got 30 embeddings, dim=256
Batch 24/87 → got 30 embeddings, dim=256

Generating embeddings:  30%|██▉       | 26/87 [00:06<00:09,  6.69it/s]

Batch 25/87 → got 30 embeddings, dim=256
Batch 28/87 → got 30 embeddings, dim=256

Generating embeddings:  31%|███       | 27/87 [00:07<00:10,  5.80it/s]

Batch 27/87 → got 30 embeddings, dim=256

Generating embeddings:  33%|███▎      | 29/87 [00:07<00:10,  5.32it/s]

Batch 31/87 → got 30 embeddings, dim=256
Batch 29/87 → got 30 embeddings, dim=256
Batch 30/87 → got 30 embeddings, dim=256

Generating embeddings:  36%|███▌      | 31/87 [00:07<00:07,  7.24it/s]

Batch 32/87 → got 30 embeddings, dim=256

Generating embeddings:  38%|███▊      | 33/87 [00:08<00:10,  5.11it/s]

Batch 34/87 → got 30 embeddings, dim=256
Batch 35/87 → got 30 embeddings, dim=256
Batch 26/87 → got 30 embeddings, dim=256

Generating embeddings:  40%|████      | 35/87 [00:08<00:07,  6.95it/s]

Batch 36/87 → got 30 embeddings, dim=256

Generating embeddings:  43%|████▎     | 37/87 [00:08<00:08,  5.76it/s]

Batch 33/87 → got 30 embeddings, dim=256
Batch 39/87 → got 30 embeddings, dim=256

Generating embeddings:  45%|████▍     | 39/87 [00:09<00:08,  5.86it/s]

Batch 37/87 → got 30 embeddings, dim=256
Batch 40/87 → got 30 embeddings, dim=256

Generating embeddings:  48%|████▊     | 42/87 [00:09<00:05,  7.79it/s]

Batch 38/87 → got 30 embeddings, dim=256
Batch 41/87 → got 30 embeddings, dim=256
Batch 42/87 → got 30 embeddings, dim=256

Generating embeddings:  51%|█████     | 44/87 [00:09<00:07,  5.91it/s]

Batch 44/87 → got 30 embeddings, dim=256
Batch 46/87 → got 30 embeddings, dim=256
Batch 43/87 → got 30 embeddings, dim=256

Generating embeddings:  53%|█████▎    | 46/87 [00:10<00:04,  8.23it/s]

Batch 47/87 → got 30 embeddings, dim=256
Batch 45/87 → got 30 embeddings, dim=256

Generating embeddings:  56%|█████▋    | 49/87 [00:10<00:06,  5.90it/s]

Batch 52/87 → got 30 embeddings, dim=256
Batch 51/87 → got 30 embeddings, dim=256
Batch 49/87 → got 30 embeddings, dim=256
Batch 50/87 → got 30 embeddings, dim=256

Generating embeddings:  60%|█████▉    | 52/87 [00:11<00:05,  6.17it/s]

Batch 54/87 → got 30 embeddings, dim=256
Batch 48/87 → got 30 embeddings, dim=256

Generating embeddings:  62%|██████▏   | 54/87 [00:11<00:04,  6.80it/s]

Batch 55/87 → got 30 embeddings, dim=256
Batch 53/87 → got 30 embeddings, dim=256
Batch 56/87 → got 30 embeddings, dim=256

Generating embeddings:  67%|██████▋   | 58/87 [00:11<00:03,  7.26it/s]

Batch 57/87 → got 30 embeddings, dim=256
Batch 58/87 → got 30 embeddings, dim=256
Batch 61/87 → got 30 embeddings, dim=256

Generating embeddings:  70%|███████   | 61/87 [00:12<00:02,  8.89it/s]

Batch 59/87 → got 30 embeddings, dim=256
Batch 60/87 → got 30 embeddings, dim=256
Batch 62/87 → got 30 embeddings, dim=256

Generating embeddings:  72%|███████▏  | 63/87 [00:12<00:03,  7.40it/s]

Batch 63/87 → got 30 embeddings, dim=256
Batch 64/87 → got 30 embeddings, dim=256

Generating embeddings:  75%|███████▍  | 65/87 [00:12<00:02,  7.90it/s]

Batch 66/87 → got 30 embeddings, dim=256
Batch 67/87 → got 30 embeddings, dim=256

Generating embeddings:  78%|███████▊  | 68/87 [00:13<00:02,  8.27it/s]

Batch 69/87 → got 30 embeddings, dim=256
Batch 65/87 → got 30 embeddings, dim=256
Batch 71/87 → got 30 embeddings, dim=256
Batch 68/87 → got 30 embeddings, dim=256

Generating embeddings:  84%|████████▍ | 73/87 [00:13<00:01,  8.15it/s]

Batch 74/87 → got 30 embeddings, dim=256
Batch 75/87 → got 30 embeddings, dim=256
Batch 72/87 → got 30 embeddings, dim=256

Generating embeddings:  86%|████████▌ | 75/87 [00:14<00:01,  7.87it/s]

Batch 70/87 → got 30 embeddings, dim=256
Batch 73/87 → got 30 embeddings, dim=256

Generating embeddings:  89%|████████▊ | 77/87 [00:14<00:01,  7.87it/s]

Batch 77/87 → got 30 embeddings, dim=256
Batch 78/87 → got 30 embeddings, dim=256

Generating embeddings:  90%|████████▉ | 78/87 [00:14<00:01,  8.25it/s]

Batch 76/87 → got 30 embeddings, dim=256

Generating embeddings:  92%|█████████▏| 80/87 [00:14<00:01,  6.28it/s]

Batch 80/87 → got 30 embeddings, dim=256
Batch 81/87 → got 30 embeddings, dim=256

Generating embeddings:  95%|█████████▌| 83/87 [00:15<00:00,  7.51it/s]

Batch 83/87 → got 30 embeddings, dim=256
Batch 82/87 → got 30 embeddings, dim=256
Batch 79/87 → got 30 embeddings, dim=256

Generating embeddings:  98%|█████████▊| 85/87 [00:15<00:00,  9.39it/s]

Batch 85/87 → got 30 embeddings, dim=256
Batch 84/87 → got 30 embeddings, dim=256
Batch 87/87 → got 11 embeddings, dim=256

Generating embeddings: 100%|██████████| 87/87 [00:15<00:00,  5.54it/s]

Batch 86/87 → got 30 embeddings, dim=256

In [36]:
final_df

,product_code,main_boost,low_value_flag,popularity,product_id,product_name,category_name,brand_name,price_cash,link,index,description,embedding
0,408-0009SI,1,0,0.700122,1155,MOTOCULTOR TF545DE ARRANQUE ELECTRICO ...,MOTOCULTORES ...,HUSQVARNA ...,2300.0000,[https://campomaq.blob.core.windows.net/campom...,"[0, 2, 3]",Motocultor Husqvarna TF545DE con arranque eléc...,"[-0.051276810467243195, 0.03325275704264641, 0..."
1,700-0001,1,0,0.423942,3189,MOTOCULTOR TKC-450 ...,MOTOCULTORES ...,MITSUBISHI ...,5400.0000,[https://campomaq.blob.core.windows.net/campom...,[0],Motocultor Mitsubishi TKC-450: rendimiento y m...,"[0.06657266616821289, 0.04838528856635094, -0...."
2,700M-578,1,0,0.240174,4482,MOTOCULTOR TOPO Y LEVANTACAMAS ...,MOTOCULTORES ...,VARIOS MOTORES ...,0.0000,NaN,NaN,Motocultor Topo y Levantacamas: versátil para ...,"[-0.006642810069024563, -0.018496418371796608,..."
3,700M-490SI,1,1,0.230856,4285,CUCHILLA CURVA IZQUIERDA APORCAR MOTOCULTOR TF...,ACCESORIOS MOTOCULTORES ...,HUSQVARNA ...,7.7500,NaN,NaN,Cuchilla curva izquierda para Motocultor TF545...,"[-0.018200406804680824, -0.050819557160139084,..."
4,700M-491SI,1,1,0.230580,4286,CUCHILLA CURVA DERECHA APORCAR MOTOCULTOR TF54...,ACCESORIOS MOTOCULTORES ...,HUSQVARNA ...,7.5000,NaN,NaN,Cuchilla curva derecha para Motocultor TF545DE...,"[-0.04149997979402542, -0.025535432621836662, ..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2586,700B-331,0,0,0.000000,4227,LANZA CIRCULAR 5 SALIDAS ALUMINIO ...,ACCESORIOS FUMIGACION ...,VARIOS BOMBAS ...,0.0000,NaN,NaN,Lanza circular de aluminio 5 salidas – accesor...,"[0.0019159537041559815, 0.02917078696191311, 0..."
2587,700M-311,0,0,0.000000,2487,"LLAVE 3/4"" MEDIA VUELTA ...",ACCESORIOS DE RIEGO ...,VARIOS BOMBAS ...,10.7202,[https://campomaq.blob.core.windows.net/campom...,[0],Llave de 3/4 pulgadas media vuelta – accesorio...,"[0.045564282685518265, -0.021175028756260872, ..."
2588,700B-345,0,0,0.000000,2314,BANDA A-26 ...,ACCESORIOS FUMIGACION ...,VARIOS BOMBAS ...,4.8345,NaN,NaN,Banda A-26 – accesorio de fumigación para apli...,"[-0.029080022126436234, -0.03343086689710617, ..."
2589,440-0051,0,0,0.000000,1718,GUIA DE TEMPLADOR 365 ...,REPUESTOS MOTOSIERRAS ...,HUSQVARNA ...,7.3000,[https://campomaq.blob.core.windows.net/campom...,[0],Guía de templador 365 para motosierras Husqvar...,"[-0.06599218398332596, -0.005882462952286005, ..."
2590,406-0002,0,0,0.000000,4312,CARBURADOR MS-125 ...,REPUESTOS MOTOSIERRAS ...,HUSQVARNA ...,59.0000,NaN,NaN,Carburador MS-125 para Husqvarna – rendimiento...,"[0.05404164269566536, -0.007189377676695585, -..."

In [38]:
mongo_uri = os.environ['MONGO_URI']
client = MongoClient(mongo_uri, server_api=ServerApi('1'))

if cm_env == 'prod':
    collection = client["campomaq"]["cm_catalog"]
else:
    collection = client["campomaq_test"]["cm_catalog"]

if not final_df.empty:
    # Convert DataFrame to JSON
    records = final_df.to_dict(orient="records")
    collection.insert_many(records)
    print(f"✅ Inserted {len(records)} records into MongoDB")

else:
    print("No new data to insert.")

✅ Inserted 2591 records into MongoDB

# New field to indicate that the product is shown in the catalogm

In [6]:
# Select the database and collection
cm_env = os.environ.get('CM_ENV', 'dev')
if cm_env == 'prod':
    collection = client["campomaq"]["cm_catalog"]
else:
    collection = client["campomaq_test"]["cm_catalog"]

# New field to indicate that the product is shown in the catalog
top_100_codes = (
    df_top_sales_prods.sort_values("popularity", ascending=False)
    .head(100)["product_code"]
    .tolist()
)

# Assign True for top 100, False for others
df_top_sales_prods["show_in_app"] = df_top_sales_prods["product_code"].isin(top_100_codes)

from pymongo import UpdateOne

# Build bulk operations
operations = [
    UpdateOne(
        {"product_code": row["product_code"]},
        {"$set": {"show_in_app": bool(row["show_in_app"])}}
    )
    for _, row in df_top_sales_prods.iterrows()
]
# Execute in bulk
if operations:
    result = collection.bulk_write(operations, ordered=False)
    print(f"Matched: {result.matched_count}, Modified: {result.modified_count}")

Matched: 2591, Modified: 2591